### ISSUE TITLE
Target Rate data not available after HA Start/Restart

### ISSUE THREAD

**Issue by Stephens-ely** [BottlecapDave/HomeAssistant-OctopusEnergy#1025]
### Describe the bug

I've upgraded to V13 of the integration - Since then, after a HA restart, my target rate sensors don't get populated and I have to force it manually - I've waited over an hour to see if it's a timing issue but it doesn't appear to be.

### Reproduction steps

Restart HA and check attributes of sensor

### Expected behaviour

On previous versions the data was still there are a restart

### Tariff Code

E-1R-AGILE-23-12-06-L

### Integration Version

13.0.0

### Home Assistant Version

2024.10.2

### Fresh Install?

After upgrading

### Home Assistant Logs

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/octopus_energy/target_rates/target_rate.py:143
integration: Octopus Energy (documentation, issues)
First occurred: 11:01:24 (2 occurrences)
Last logged: 11:02:24

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/octopus_energy/target_rates/target_rate.py", line 143, in _handle_coordinator_update
    if (current_date.minute % 30) == 0 or len(self._target_rates) == 0 or self._last_evaluated is None or self._last_evaluated + timedelta(minutes=30) < current_date:
                                          ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by petebanham** [comment]
I had a similar, but not identical issue when I upgraded the other day,  in that 1 of my 3 target rates would not refresh/populate. Restating HA or reloading the integration didn't work but strangely when I gave up and added a new one instead,  both the new and original one updated.  I rolled back the integration to 12.2.1 and it been fine since then .  HA version 2024.10.2.

**Comment by BottlecapDave** [comment]
Hello and sorry you're seeing this issue. I'll try and get a fix out tonight.

**Comment by Stephens-ely** [comment]
Thanks. It’s much appreciated

**Comment by BottlecapDave** [comment]
The fix for the reported log error has been released as part of [v13.0.1](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.0.1). This should fix your issue.

**Comment by alfwro13** [comment]
I am sorry to say that issue is not resolved in v13.0.1
I upgraded from version 12.2.1 and I was getting a lot of errors like this one:
```
2024-10-17 08:56:54.790 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/octopus_energy/target_rates/target_rate.py", line 237, in _handle_coordinator_update
    active_result = get_target_rate_info(current_date, self._target_rates, offset)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/target_rates/__init__.py", line 239, in get_target_rate_info
    total_applicable_rates = len(applicable_rates)
                             ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```
Downgraded back to 12.2.1 and all is good again.

**Comment by BottlecapDave** [comment]
Sorry to hear this. I'm struggling to recreate the issue on my end. I've released https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.0.2-beta.1 which should hopefully fix the issue.

**Comment by alfwro13** [comment]
Just tested it - 13.0.2b1 fixed it.
Thank you.

**Comment by BottlecapDave** [comment]
Thanks for the update. This has now been released properly at v13.0.2.

**Comment by martymcfly1** [comment]
I have a similar issue - have just updated to the latest version as well.

Here is the error log:

Logger: homeassistant
Source: custom_components/octopus_energy/target_rates/__init__.py:273
integration: Octopus Energy ([documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy), [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues))
First occurred: 12:06:42 (1 occurrences)
Last logged: 12:06:42

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/octopus_energy/target_rates/target_rate.py", line 237, in _handle_coordinator_update
    active_result = get_target_rate_info(current_date, self._target_rates, offset)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/target_rates/__init__.py", line 273, in get_target_rate_info
    "average_cost": total_cost / (minutes / 30),
                    ~~~~~~~~~~~^~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero

**Comment by Stephens-ely** [comment]
I’m afraid ai’ve had to roll back to v12.x as I’m having issues with v13 not updating target rates either when HA is rebooted or when new rates are published at 4pm. V12 does both perfectly

**Comment by BottlecapDave** [comment]
@Stephens-ely are you still having issues? If so, please raise a new issue and provide diagnostics as per the faq along with any errors that might be present in the home assistant logs
