### ISSUE TITLE
Failed to start up since latest version

### ISSUE THREAD

**Issue by mlamport** [BottlecapDave/HomeAssistant-OctopusEnergy#1078]
### Describe the bug

Octopus Entities not loading since the last update.

See exception below:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 143, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 399, in async_setup_dependencies
    await async_save_cached_intelligent_device(hass, account_id, intelligent_device)
  File "/config/custom_components/octopus_energy/storage/intelligent_device.py", line 29, in async_save_cached_intelligent_device
    await store.async_save(intelligent_device.to_dict(omit_id=False))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to_dict'

### Reproduction steps

On Start up

### Expected behaviour

To Load up

### Tariff Code

N/A

### Integration Version

13.1.2

### Home Assistant Version

Core 2024.11.1 Supervisor 2024.11.3 Operating System 13.2 Frontend 20241106.2

### Fresh Install?

Not specified

### Home Assistant Logs

See exception below:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 143, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 399, in async_setup_dependencies
    await async_save_cached_intelligent_device(hass, account_id, intelligent_device)
  File "/config/custom_components/octopus_energy/storage/intelligent_device.py", line 29, in async_save_cached_intelligent_device
    await store.async_save(intelligent_device.to_dict(omit_id=False))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to_dict'

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by Dave-Parry** [comment]
Me too, had to install a backup pre update and not install update to cure.

**Comment by BottlecapDave** [comment]
Hello and sorry you've seen this issue. This should be rectified as part of v13.1.3
