### ISSUE TITLE
Entities no longer available - ACCOUNT error

### ISSUE THREAD

**Issue by alienatedsec** [BottlecapDave/HomeAssistant-OctopusEnergy#111]
**Describe the bug**

It stopped feeding sensors. `This entity is no longer being provided by the octopus_energy integration. If the entity is no longer in use, delete it in settings.` on all of them.

**To Reproduce**

Still trying to figure it out. An upgrade from 2022.12.7 to 2022.12.8?

**Expected behavior**

Working as normal

**Home Assistant Version**

2022.12.8

**Integration Version**

v5.0.0

**Fresh Install?**

An upgrade of Home Assistant potentially killed it

**Home Assistant Logs**
```
Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/sensor.py:119
Integration: Sensor (documentation, issues)
First occurred: 22 December 2022 at 23:31:12 (5 occurrences)
Last logged: 22 December 2022 at 23:59:33

Error while setting up octopus_energy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/octopus_energy/sensor.py", line 95, in async_setup_entry
    await async_setup_default_sensors(hass, entry, async_add_entities)
  File "/config/custom_components/octopus_energy/sensor.py", line 119, in async_setup_default_sensors
    account_info = hass.data[DOMAIN][DATA_ACCOUNT]
KeyError: 'ACCOUNT'
```
```
2022-12-22 23:18:32.268 INFO (MainThread) [homeassistant.setup] Setting up octopus_energy
2022-12-22 23:18:32.268 INFO (MainThread) [homeassistant.setup] Setup of domain octopus_energy took 0.0 seconds
2022-12-22 23:18:37.473 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Octopus Energy for octopus_energy
File "/config/custom_components/octopus_energy/__init__.py", line 41, in async_setup_entry
File "/config/custom_components/octopus_energy/__init__.py", line 95, in async_setup_dependencies
File "/config/custom_components/octopus_energy/api_client.py", line 125, in async_get_account
File "/config/custom_components/octopus_energy/api_client.py", line 114, in async_refresh_token
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.octopus.energy:443 ssl:default [Try again]
2022-12-22 23:31:11.397 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.octopus_energy
2022-12-22 23:31:11.402 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.octopus_energy
2022-12-22 23:31:12.766 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up octopus_energy platform for sensor
File "/config/custom_components/octopus_energy/sensor.py", line 95, in async_setup_entry
File "/config/custom_components/octopus_energy/sensor.py", line 119, in async_setup_default_sensors
2022-12-22 23:47:15.305 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.octopus_energy
2022-12-22 23:47:15.306 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Octopus Energy for binary_sensor
2022-12-22 23:47:15.310 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up octopus_energy platform for sensor
File "/config/custom_components/octopus_energy/sensor.py", line 95, in async_setup_entry
File "/config/custom_components/octopus_energy/sensor.py", line 119, in async_setup_default_sensors
2022-12-22 23:47:35.646 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.octopus_energy
2022-12-22 23:47:35.647 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Octopus Energy for binary_sensor
2022-12-22 23:47:35.650 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up octopus_energy platform for sensor
File "/config/custom_components/octopus_energy/sensor.py", line 95, in async_setup_entry
File "/config/custom_components/octopus_energy/sensor.py", line 119, in async_setup_default_sensors
2022-12-22 23:54:59.174 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.octopus_energy
2022-12-22 23:54:59.174 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Octopus Energy for binary_sensor
2022-12-22 23:54:59.176 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up octopus_energy platform for sensor
File "/config/custom_components/octopus_energy/sensor.py", line 95, in async_setup_entry
File "/config/custom_components/octopus_energy/sensor.py", line 119, in async_setup_default_sensors
2022-12-22 23:59:33.187 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.octopus_energy
2022-12-22 23:59:33.188 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Octopus Energy for binary_sensor
2022-12-22 23:59:33.194 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up octopus_energy platform for sensor
File "/config/custom_components/octopus_energy/sensor.py", line 95, in async_setup_entry
File "/config/custom_components/octopus_energy/sensor.py", line 119, in async_setup_default_sensors
```

**Comment by BottlecapDave** [comment]
Based upon this line

> Cannot connect to host api.octopus.energy:443 ssl:default [Try again]

It looks like it failed to retrieve the account upon initialisation (api was down? or internet failed?). If you reload the integration or reboot your Home Assistant instance, it should be fine. I'll try and add some clearer error messages.

**Comment by alienatedsec** [comment]
Hi @BottlecapDave 

Unfortunately, it's not a problem with the connection despite the error. I reloaded it multiple times and checked all areas where it could fail. Still the same.

Any other ideas why it could be failing? Any dependencies in the latest update? All sensors are still unavailable.
