### ISSUE TITLE
Broken after upgrade to HA 2023.1.5

### ISSUE THREAD

**Issue by adamlc** [BottlecapDave/HomeAssistant-OctopusEnergy#124]
**Describe the bug**

After upgrading to HA 2023.1.5 the integration seems to no longer be working. Its possible it might have broken before the upgrade and I didn't notice!

I have also tried to remove the integration and add it again, but get the same error. Also tried re-creating the API key too.

**To Reproduce**

Upgrade to HA 2023.1.5

**Expected behavior**

The integration to load all entities

**Home Assistant Version**

2023.1.5

**Integration Version**

5.2.1

**Fresh Install?**

After an upgrade.

**Home Assistant Logs**

```
homeassistant  | 2023-01-18 10:48:45.093 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Octopus Energy for binary_sensor
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
homeassistant  |     result = await component.async_setup_entry(hass, self)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
homeassistant  |     return await component.async_setup_entry(entry)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 166, in async_setup_entry
homeassistant  |     raise ValueError("Config entry has already been setup!")
homeassistant  | ValueError: Config entry has already been setup!
homeassistant  | 2023-01-18 10:48:45.095 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up octopus_energy platform for sensor
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
homeassistant  |     await asyncio.shield(task)
homeassistant  |   File "/config/custom_components/octopus_energy/sensor.py", line 93, in async_setup_entry
homeassistant  |     await async_setup_default_sensors(hass, entry, async_add_entities)
homeassistant  |   File "/config/custom_components/octopus_energy/sensor.py", line 113, in async_setup_default_sensors
homeassistant  |     account_info = hass.data[DOMAIN][DATA_ACCOUNT]
homeassistant  | KeyError: 'ACCOUNT'
```

**Comment by adamlc** [comment]
Well weirdly over night it began working again!

Maybe there was a weird issue the Octopus API. I shall monitor and open up a new issue with debug logs if it occurs again :)
