### ISSUE TITLE
Add on doesn't load (TypeError: argument of type 'NoneType' is not iterable)

### ISSUE THREAD

**Issue by rossdargan** [BottlecapDave/HomeAssistant-OctopusEnergy#126]
**Describe the bug**

The app crashes handling the response from the API call

**To Reproduce**

2023.1.5

**Expected behavior**

It doesn't load - it should :-)

**Home Assistant Version**

The version of Home Assistant.

**Integration Version**

5.2.1

**Fresh Install?**

No, updated

**Home Assistant Logs**

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/octopus_energy/__init__.py", line 41, in async_setup_entry
    await async_setup_dependencies(hass, entry.data)
  File "/config/custom_components/octopus_energy/__init__.py", line 95, in async_setup_dependencies
    account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
  File "/config/custom_components/octopus_energy/api_client.py", line 140, in async_get_account
    "electricity_meter_points": list(map(lambda mp: {
  File "/config/custom_components/octopus_energy/api_client.py", line 147, in <lambda>
    "agreements": list(map(lambda a: {
  File "/config/custom_components/octopus_energy/api_client.py", line 150, in <lambda>
    "tariff_code": a["tariff"]["tariffCode"] if "tariffCode" in a["tariff"] else None,
TypeError: argument of type 'NoneType' is not iterable

**Comment by BottlecapDave** [comment]
Sorry to hear you're having issues with the plugin. I've seen this pop up a few times, but stuggled to recreate. For some users, it doesn't happen consistently and so I think it's the API not behaving properly. I _thought_ I added enough defensive code, but apparently not.

If you are able to recreate this, it would be useful if you could turn on debug logging for the integration (instructions in the readme) and post the account response. This should be in the form of something like
```
{ "data": { "account": ... } }
```

feel free to "star" anything you feel is identifiable data for you - I'm more interested in the structure :)
