### ISSUE TITLE
Error when valid_from is not provided

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-OctopusEnergy#13]
I'm also having issues seeing the sensors in HA. Any help would be greatly appreciated. I get the following two Error:

1) Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:161 
Integration: Sensor (documentation, issues) 
First occurred: 10:40:11 PM (1 occurrences) 
Last logged: 10:40:11 PM

Error while setting up octopus_energy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 89, in async_update_data
    hass.data[DOMAIN][DATA_RATES] = await client.async_get_rates(product_code, tariff_code)
  File "/config/custom_components/octopus_energy/api_client.py", line 48, in async_get_rates
    valid_from = as_utc(parse_datetime(item["valid_from"]))
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 133, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/octopus_energy/sensor.py", line 40, in async_setup_entry
    await async_setup_default_sensors(hass, entry, async_add_entities)
  File "/config/custom_components/octopus_energy/sensor.py", line 56, in async_setup_default_sensors
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: argument 1 must be str, not None

2) This error originated from a custom integration.

Logger: custom_components.octopus_energy
Source: util/dt.py:133 
Integration: Octopus Energy (documentation, issues) 
First occurred: 10:40:11 PM (1 occurrences) 
Last logged: 10:40:11 PM

Unexpected error fetching rates data: argument 1 must be str, not None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 89, in async_update_data
    hass.data[DOMAIN][DATA_RATES] = await client.async_get_rates(product_code, tariff_code)
  File "/config/custom_components/octopus_energy/api_client.py", line 48, in async_get_rates
    valid_from = as_utc(parse_datetime(item["valid_from"]))
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 133, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not None

Hope you can help been trying to get Octopus into HA for a while now

_Originally posted by @jimdhope in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/12#issuecomment-930568486_

**Comment by BottlecapDave** [comment]
This issue has now been fixed.
