### ISSUE TITLE
Unable to extract product code from tarriff code

### ISSUE THREAD

**Issue by bnuttall** [BottlecapDave/HomeAssistant-OctopusEnergy#172]
Until about a month ago, the integration was working fine and showed the sensors I expected. Somewhat mysteriously stopped working, just got around to capturing the logs.

I get the following two errors in the logs on startup of the integration. This might be happening because I'm on a special legacy import tariff for people who participated in the Powerloop V2G experiment -- probably only about 50 of us or so on this tariff, so it might not be something the integration is expecting to see.

```
This error originated from a custom integration.

Logger: custom_components.octopus_energy
Source: custom_components/octopus_energy/utils.py:14
Integration: Octopus Energy (documentation, issues)
First occurred: 2:22:06 PM (1 occurrences)
Last logged: 2:22:06 PM

Unexpected error fetching rates data: Unable to extract product code from tariff code: V2G-EXPORT-12M-FIXED-22-12-01-C
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 139, in async_update_electricity_rates_data
    new_rates = await client.async_get_electricity_rates(tariff_code, is_smart_meter, period_from, period_to)
  File "/config/custom_components/octopus_energy/api_client.py", line 304, in async_get_electricity_rates
    tariff_parts = get_tariff_parts(tariff_code)
  File "/config/custom_components/octopus_energy/utils.py", line 14, in get_tariff_parts
    raise Exception(f'Unable to extract product code from tariff code: {tariff_code}')
Exception: Unable to extract product code from tariff code: V2G-EXPORT-12M-FIXED-22-12-01-C
```

```
Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:211
Integration: Sensor (documentation, issues)
First occurred: 2:22:06 PM (1 occurrences)
Last logged: 2:22:06 PM

Error while setting up octopus_energy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 139, in async_update_electricity_rates_data
    new_rates = await client.async_get_electricity_rates(tariff_code, is_smart_meter, period_from, period_to)
  File "/config/custom_components/octopus_energy/api_client.py", line 304, in async_get_electricity_rates
    tariff_parts = get_tariff_parts(tariff_code)
  File "/config/custom_components/octopus_energy/utils.py", line 14, in get_tariff_parts
    raise Exception(f'Unable to extract product code from tariff code: {tariff_code}')
Exception: Unable to extract product code from tariff code: V2G-EXPORT-12M-FIXED-22-12-01-C

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/octopus_energy/sensor.py", line 126, in async_setup_entry
    await async_setup_default_sensors(hass, entry, async_add_entities)
  File "/config/custom_components/octopus_energy/sensor.py", line 138, in async_setup_default_sensors
    await rate_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 211, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Unable to extract product code from tariff code: V2G-EXPORT-12M-FIXED-22-12-01-C
```

**Comment by bnuttall** [comment]
Ok from looking at the regex you are using to in test_tariff_parts.py, it doesn't look like you are expecting the format of my specific export tarriff code to come through.

V2G-EXPORT-12M-FIXED-22-12-01-C

Also, looking at the dump of what the integration thinks my tariff codes are, it just lists two when I have three (one import each for elec and gas, and the above export). The first log message lists all three but the second log message only picks up the first two?

```
2023-03-15 15:08:06.298 DEBUG (MainThread) [custom_components.octopus_energy.api_client] {'data': {'account': {'electricityAgreements': [{'meterPoint': {'mpan': '1200062698240', 'meters': [{'serialNumber': '19L3740707', 'smartExportElectricityMeter': {'deviceId': '30-EB-5A-FF-FF-05-D4-13'}, 'smartImportElectricityMeter': None}], 'agreements': [{'validFrom': '2023-01-14T00:00:00+00:00', 'validTo': '2024-01-14T00:00:00+00:00', 'tariff': {'tariffCode': 'V2G-EXPORT-12M-FIXED-22-12-01-C'}}]}}, {'meterPoint': {'mpan': '1200041472908', 'meters': [{'serialNumber': '19L3740707', 'smartExportElectricityMeter': None, 'smartImportElectricityMeter': {'deviceId': '30-EB-5A-FF-FF-05-D4-13'}}], 'agreements': [{'validFrom': '2023-01-14T00:00:00+00:00', 'validTo': None, 'tariff': {'tariffCode': 'E-1R-INTELLI-VAR-22-10-14-C'}}]}}], 'gasAgreements': [{'meterPoint': {'mprn': '501413504', 'meters': [{'serialNumber': 'E6S12271672061', 'consumptionUnits': 'm³'}], 'agreements': [{'validFrom': '2023-01-14T00:00:00+00:00', 'validTo': None, 'tariff': {'tariffCode': 'G-1R-VAR-22-10-01-C'}}]}}]}}}

2023-03-15 15:08:06.302 DEBUG (MainThread) [custom_components.octopus_energy] tariff_codes: {('1200062698240', True): 'V2G-EXPORT-12M-FIXED-22-12-01-C', ('1200041472908', True): 'E-1R-INTELLI-VAR-22-10-14-C'}
```

**Comment by BottlecapDave** [comment]
Hello @bnuttall.

Sorry that the tariff is causing issues and glad to see that OE have gone against their standards :( This one might be more tricky, as I'm struggling to find the related product or rates via the API.

**Comment by BottlecapDave** [comment]
Hi @bnuttall.

I've created a new release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.3.0) which retrieves the product code with the account information. You _might_ be able to retrieve this information via the diagnostics on the meter devices, but more than likely you'll need to retrieve the raw response from the logs (you'll need `debug` level - see readme). If you could post the result here (redacting any serial numbers/device ids) it might help point me in the right direction.

**Comment by bnuttall** [comment]
Here's the diagnostics from my offending meter.

Really nice changes in 6.4.0, I can see the meter in Home Assistant now even though it still falls on its face when it tries to retrieve the tariff details.

[octopus_energy-55b4e412878fc7729b90605f71e3840d-Electricity Meter-69fe3b0799d13e2892b591a0c8f55d34.json.txt](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/11139096/octopus_energy-55b4e412878fc7729b90605f71e3840d-Electricity.Meter-69fe3b0799d13e2892b591a0c8f55d34.json.txt)

**Comment by BottlecapDave** [comment]
Thanks for the update. I will adjust the code to handle this possible structure. Unfortunately though the data isn't available via the API for some reason. I've raised an issue in the OE forums and await some response https://forum.octopus.energy/t/v2g-product-and-rates-not-found/7390

**Comment by BottlecapDave** [comment]
The latest release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.5.0) now correctly identifies your tariff, however it should highlight a different message stating the product isn't available (as above)

**Comment by BottlecapDave** [comment]
Hello. I've had an update in the forum and it looks like there is no plans to support that tariff via the API that the integration uses 😞 I assume once the tariff comes out of experimental mode, it'll become available.

The only suggestion was to hard code the price (at the current 15p?), however I'm not wanting to do this as it will increase maintenance of the plugin when it inevitably changes and is a slipperly slope for the various tariffs.
