### ISSUE TITLE
Error - object is not subscriptable - started 10th March

### ISSUE THREAD

**Issue by jksj461** [BottlecapDave/HomeAssistant-OctopusEnergy#182]
This integration (HomeAssistant-OctopusEnergy-5.1.0) stopped working on the 10th or 11th March. There was no corresponding change to HA or this integration so I suspect that Octopus changed something. I had previously 6 months running without any issues. It my be related to the fact that I have 3 accounts, two of which are obsolete relating to the takeover by Octopus of Engie. These first two accounts have no data associated with them. 
The standard curl commands mentioned on the Octopus Developer Page do still work though.
curl -u "sk_live_key******" "https://api.octopus.energy/v1/electricity-meter-points/*****/meters/****/consumption/" 
produces consumption data.
Home Assistant Log
2023-03-21 12:36:08.184 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration octopus_energy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-21 12:36:30.234 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Octopus Energy for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/octopus_energy/__init__.py", line 41, in async_setup_entry
    await async_setup_dependencies(hass, entry.data)
  File "/config/custom_components/octopus_energy/__init__.py", line 95, in async_setup_dependencies
    account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
  File "/config/custom_components/octopus_energy/api_client.py", line 152, in async_get_account
    }, account_response_body["data"]["account"]["electricityAgreements"])),
TypeError: 'NoneType' object is not subscriptable

**Comment by BottlecapDave** [comment]
Hello and sorry that you're having issues.

The error suggests its due to you having zero active agreements or potentially not being able to find the account (if your integration is associated with a now obsolete account - separate to the key). 

If you could follow the readme and increase the logs, then restart your HA instance and look in your logs for a payload under `DEBUG` level which should include the raw account response.

**Comment by jksj461** [comment]
Additional logging attached
[Octopus_edited.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/11038671/Octopus_edited.log)

**Comment by BottlecapDave** [comment]
Hi there. I believe I've added some more guarding around this incident in the latest release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.3.1). This should indicate that you have either an invalid account or API key configured, with instructions provided for fixing this.

**Comment by jksj461** [comment]
Octopus have offered to move the 2 defunct accounts to a new email address which might resolve this issue.
Thanks for the update - new log :-1: 
2023-03-29 07:41:52.766 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration octopus_energy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-29 07:42:16.699 WARNING (MainThread) [homeassistant.setup] Setup of schedule is taking over 10 seconds.
2023-03-29 07:42:16.709 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2023-03-29 07:42:16.712 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2023-03-29 07:42:16.714 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2023-03-29 07:42:16.717 WARNING (MainThread) [homeassistant.setup] Setup of input_button is taking over 10 seconds.
2023-03-29 07:42:16.719 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2023-03-29 07:42:16.722 WARNING (MainThread) [homeassistant.setup] Setup of timer is taking over 10 seconds.
2023-03-29 07:42:16.724 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2023-03-29 07:42:16.788 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2023-03-29 07:42:16.791 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2023-03-29 07:42:24.655 ERROR (MainThread) [custom_components.octopus_energy] Unexpected error fetching rates data: name 'ir' is not defined
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 150, in async_update_electricity_rates_data
    tariff_codes = await async_get_current_electricity_agreement_tariff_codes(hass, client, account_id)
  File "/config/custom_components/octopus_energy/__init__.py", line 91, in async_get_current_electricity_agreement_tariff_codes
    ir.async_delete_issue(hass, DOMAIN, f"account_not_found_{account_id}")
NameError: name 'ir' is not defined
2023-03-29 07:42:24.668 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up octopus_energy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/__init__.py", line 150, in async_update_electricity_rates_data
    tariff_codes = await async_get_current_electricity_agreement_tariff_codes(hass, client, account_id)
  File "/config/custom_components/octopus_energy/__init__.py", line 91, in async_get_current_electricity_agreement_tariff_codes
    ir.async_delete_issue(hass, DOMAIN, f"account_not_found_{account_id}")
NameError: name 'ir' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/octopus_energy/sensor.py", line 129, in async_setup_entry
    await async_setup_default_sensors(hass, entry, async_add_entities)
  File "/config/custom_components/octopus_energy/sensor.py", line 141, in async_setup_default_sensors
    await rate_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 211, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: name 'ir' is not defined

**Comment by BottlecapDave** [comment]
Sorry, this was caused by a silly mistake by myself that wasn't caught by my CI. I'm planning on adding some additional checks to ensure this doesn't happen again. A new release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.3.2) should rectify this, which should help identify your issue.

**Comment by jksj461** [comment]
Many thanks that seems to be working fine now.
The following fields are now showing valid data :-
Electricity 21E5222623 1610028480603 Current Rate sensor.octopus_energy_electricity_21e5222623_1610028480603_current_rate
Electricity 21E5222623 1610028480603 Current Standing Charge
sensor.octopus_energy_electricity_21e5222623_1610028480603_current_standing_charge
Electricity 21E5222623 1610028480603 Next Rate
sensor.electricity_21e5222623_1610028480603_next_rate
Electricity 21E5222623 1610028480603 Previous Accumulative Consumption
sensor.octopus_energy_electricity_21e5222623_1610028480603_previous_accumulative_consumption
Electricity 21E5222623 1610028480603 Previous Accumulative Cost
sensor.octopus_energy_electricity_21e5222623_1610028480603_previous_accumulative_cost
Electricity 21E5222623 1610028480603 Previous Rate
sensor.octopus_energy_electricity_21e5222623_1610028480603_previous_rate
Gas E6S12048452161 1596536306 Current Rate
sensor.octopus_energy_gas_e6s12048452161_1596536306_current_rate
Gas E6S12048452161 1596536306 Current Standing Charge
sensor.octopus_energy_gas_e6s12048452161_1596536306_current_standing_charge
Gas E6S12048452161 1596536306 Previous Accumulative Consumption
sensor.octopus_energy_gas_e6s12048452161_1596536306_previous_accumulative_consumption
Gas E6S12048452161 1596536306 Previous Accumulative Consumption (kWh)
sensor.gas_e6s12048452161_1596536306_previous_accumulative_consumption_kwh
Gas E6S12048452161 1596536306 Previous Accumulative Cost
sensor.octopus_energy_gas_e6s12048452161_1596536306_previous_accumulative_cost
With all other fields showing unavailable
