### ISSUE TITLE
Error Handling Request

### ISSUE THREAD

**Issue by jt1971** [BottlecapDave/HomeAssistant-OctopusEnergy#204]
Unable to connect to my Octopus account

Error noticed today; possibly related to moving from Octopus Go to Flux.

Deleted Integration and reinstalled, using correct API and account numbers
States 'Unknown error occurred' when trying to register account

Expect to reconnect to my Octopus account

The version of Home Assistant: Home Assistant 2023.4.1

The version of the integration: 6.5.0

Fresh install of the Integration.

**Home Assistant Logs**

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/octopus_energy/api_client.py:198 
Integration: Octopus Energy (documentation, issues) 
First occurred: 18:41:42 (4 occurrences) 
Last logged: 18:49:13

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/octopus_energy/config_flow.py", line 170, in async_step_user
    return await self.async_setup_initial_account(user_input)
  File "/config/custom_components/octopus_energy/config_flow.py", line 99, in async_setup_initial_account
    account_info = await client.async_get_account(user_input[CONFIG_MAIN_ACCOUNT_ID])
  File "/config/custom_components/octopus_energy/api_client.py", line 187, in async_get_account
    "electricity_meter_points": list(map(lambda mp: {
  File "/config/custom_components/octopus_energy/api_client.py", line 189, in <lambda>
    "meters": list(map(lambda m: {
  File "/config/custom_components/octopus_energy/api_client.py", line 198, in <lambda>
    else mp["meterPoint"]["makeAndType"],
KeyError: 'makeAndType'

**Comment by BottlecapDave** [comment]
This looks like it was related to the latest release. I've released https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.6.0 which should fix this issue

**Comment by jt1971** [comment]
Seems to have fixed it - thank you for resolving so quickly!
