### ISSUE TITLE
division by zero error on startup

### ISSUE THREAD

**Issue by djdarlo** [BottlecapDave/HomeAssistant-OctopusEnergy#210]
Hey - when restarting my HA setup I am seeing the following error in the logs.

Logger: homeassistant.components.binary_sensor
Source: custom_components/octopus_energy/binary_sensors/__init__.py:224
Integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 9:17:44 AM (2 occurrences)
Last logged: 9:17:44 AM

Error adding entities for domain binary_sensor with platform octopus_energy
Error while setting up octopus_energy platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/octopus_energy/binary_sensors/target_rate.py", line 156, in is_on
    active_result = get_target_rate_info(current_date, self._target_rates, offset)
  File "/config/custom_components/octopus_energy/binary_sensors/__init__.py", line 224, in get_target_rate_info
    "overall_average_cost": round(overall_total_cost / total_applicable_rates, 5),
ZeroDivisionError: division by zero

I think this may be related to a target config I have which is set from 00:00 to 06:00 which is showing as unavailable and also this message.

This entity is no longer being provided by the octopus_energy integration. If the entity is no longer in use, delete it in settings.

**Comment by corvus2606** [comment]
I'm seeing the same error, My target runs from 22:00 - 07:00.  targets that don't cross midnight seem to be working ok.

**Comment by BottlecapDave** [comment]
Sorry about this bug. This was caused when no applicable rates were found within your block. 

This should be fixed in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v6.6.1

**Comment by corvus2606** [comment]
thanks for the quick fix!

**Comment by djdarlo** [comment]
thanks for the super quick fix
