### ISSUE TITLE
Gas no longer working since recent updates

### ISSUE THREAD

**Issue by Krotu** [BottlecapDave/HomeAssistant-OctopusEnergy#213]
I did an update through HACS yesterday, I think it jumped 3 versions? After the update none of my electric/gas sensors were working (all showed as unknown). After removing OctopusEnergy and re-adding it (lost all my history :( ) the electric now works but the gas is only partially working, it is missing the previous consumption and previous cost values. The error from the logs is as follows:

`Unexpected error fetching gas_rates_G-1R-VAR-22-11-01-G data: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/octopus_energy/sensor.py", line 136, in async_update_data
    if (rate_key not in hass.data[DOMAIN] or (current.minute % 30) == 0 or len(hass.data[DOMAIN][rate_key]) == 0):
TypeError: object of type 'NoneType' has no len()`

**Comment by Krotu** [comment]
ignore this, it seemed to resolve itself after a while.
