### ISSUE TITLE
Error adding entities for domain sensor with platform octopus_energy on startup

### ISSUE THREAD

**Issue by BobC76** [BottlecapDave/HomeAssistant-OctopusEnergy#360]
### Describe the bug

I see the log message below on startup. Its not clear what the impact is but  my gas sensor 

`sensor.octopus_energy_gas_[mpan]_previous_accumulative_consumption_kwh` 

seems to only have data from 1pm to 8.30pm yesterday.

### Reproduction steps

I see this on start up, not sure what to say to reproduce it.

### Expected behaviour

Not to see an error message in the logs on startup

### Integration Version

v8.0.0

### Home Assistant Version

Home Assistant 2023.8.1 Supervisor 2023.08.1 Operating System 10.4 Frontend 20230802.0 - latest

### Fresh Install?

Not specified

### Home Assistant Logs

```
Logger: homeassistant.components.sensor
Source: custom_components/octopus_energy/electricity/current_accumulative_cost.py:148
Integration: Sensor (documentation, issues)
First occurred: 16:39:15 (2 occurrences)
Last logged: 16:39:15

Error adding entities for domain sensor with platform octopus_energy
Error while setting up octopus_energy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/octopus_energy/electricity/current_accumulative_cost.py", line 148, in async_added_to_hass
    self._last_reset = datetime.strptime(state.attributes[x], "%Y-%m-%dT%H:%M:%S%z")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-08-08T16:35:42.170784+01:00' does not match format '%Y-%m-%dT%H:%M:%S%z'

```

**Comment by BottlecapDave** [comment]
Hello and sorry that you've encountered this issue. This should be fixed in a future release.

**Comment by BottlecapDave** [comment]
This should now be resolved in the latest release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.1.0). You might get one more instance of this bug, but going forward it should be resolved.
