### ISSUE TITLE
Peak and Off Peak Sensors Missing 30 Minute Interval Data

### ISSUE THREAD

**Issue by jasonwfrancis1** [BottlecapDave/HomeAssistant-OctopusEnergy#365]
### Describe the bug

I am trying to add my peak and off peak sensors to the energy dashboard using the instructions. I can add the total accumulative entity with the cost and it shows in intervals correctly, as does the gas.

When i add the peak and non peak, it just shows as a single value on the day the sensor was updated.

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/6323379/376e33da-79fd-41c6-a63f-a5f760e2f877)

The senor attributes do not contain the breakdown of the data like tot total sensors do.

Is this expected?

### Reproduction steps

View the peak and off peak sensors, the granular attributes are missing.

### Expected behaviour

Attricutes should be populated as per the instructions for the energy dashboard

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-L

### Integration Version

8.0

### Home Assistant Version

2023.8.1

### Fresh Install?

Not specified

### Home Assistant Logs

2023-08-10 12:28:47.674 WARNING (MainThread) [custom_components.octopus_energy.coordinators.saving_sessions] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:47.675 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:47.677 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:47.677 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_electricity_22l4466687_2700005559008_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-08-10 12:28:47.678 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:47.680 ERROR (MainThread) [homeassistant.components.sensor] octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/standing_charge.py", line 68, in async_update
    standard_charge_result = self.coordinator.data[self._mpan] if self.coordinator.data is not None and self._mpan in self.coordinator.data else None
                                                                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2023-08-10 12:28:47.684 ERROR (MainThread) [homeassistant.components.sensor] octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/gas/standing_charge.py", line 74, in async_update
    standard_charge_result = self.coordinator.data[self._mprn] if self.coordinator.data is not None and self._mprn in self.coordinator.data else None
                                                                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2023-08-10 12:28:47.686 WARNING (MainThread) [custom_components.octopus_energy.coordinators.saving_sessions] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:47.697 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_gas_e6s13050402361_7746671805_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-08-10 12:28:48.126 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:48.148 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:48.150 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:48.151 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:48.187 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.830 WARNING (MainThread) [custom_components.octopus_energy.coordinators.saving_sessions] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.831 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.832 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.832 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_electricity_22l4466687_2700005559008_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-08-10 12:28:51.833 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.834 ERROR (MainThread) [homeassistant.components.sensor] octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/standing_charge.py", line 68, in async_update
    standard_charge_result = self.coordinator.data[self._mpan] if self.coordinator.data is not None and self._mpan in self.coordinator.data else None
                                                                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2023-08-10 12:28:51.837 ERROR (MainThread) [homeassistant.components.sensor] octopus_energy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/gas/standing_charge.py", line 74, in async_update
    standard_charge_result = self.coordinator.data[self._mprn] if self.coordinator.data is not None and self._mprn in self.coordinator.data else None
                                                                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2023-08-10 12:28:51.840 WARNING (MainThread) [custom_components.octopus_energy.coordinators.saving_sessions] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.846 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_gas_e6s13050402361_7746671805_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-08-10 12:28:52.559 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:52.564 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:52.615 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:52.616 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:52.642 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.

**Comment by BottlecapDave** [comment]
Hello and sorry that you're having issues. Is it the current accumulative peak/off peak sensors you're trying to add or the previous accumulative peak/off peak sensors?

**Comment by jasonwfrancis1** [comment]
I'm using previous. The problem is it includes it on the wrong date as it stands now e.g. my yesterday day shows in today on the energy monitor for peak and off peak because there is no breakdown the same as the total. This is whether you show it in the main consumption part or the individual devices.

**Comment by BottlecapDave** [comment]
This is unfortunately a limitation in the entities, the energy dashboard and historic data, which is why a separate sensor is produced as part of the accumulative sensor. I'll add it to my list to produce a similar sensor for peak/off peak sensors

**Comment by BottlecapDave** [comment]
Sorry I was having a moment when I made the last comment. 

There should already be specific sensors for displaying peak/off peak in the dashboard. These are separate sensors to the standard sensors because as previously mentioned the standard sensors can't have historical data altered. If you follow the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/energy_dashboard.md#for-electricity-1), you should have separate peak/off peak sensors which can be added to the dashboard and provide the breakdown you're after

**Comment by jasonwfrancis1** [comment]
The sensors mentioned in the docs, which I am tying to use, do not have a cumulative data in them. The screenshot above is for the peak sensor.

**Comment by jasonwfrancis1** [comment]
This has started working now. I removed the sensors and re-added them and it works as expected now.
