### ISSUE TITLE
Electricity and Gas Standing Charges Always Unvailable

### ISSUE THREAD

**Issue by addrum** [BottlecapDave/HomeAssistant-OctopusEnergy#379]
### Describe the bug

Electricity and Gas Standing Charges Always Unvailable.
Have tried readding the integration, reloading it, and restarting Home Assistant but neither have ever come through.

### Reproduction steps

Set up integration via HACS using a Home Mini device.

### Expected behaviour

Standing charge sensors to have a numerical value.

### Integration Version

8.1.0

### Home Assistant Version

2023.8.2

### Fresh Install?

Fresh install

### Home Assistant Logs

```
This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.electricity_standing_charges
Source: custom_components/octopus_energy/coordinators/electricity_standing_charges.py:42
Integration: Octopus Energy (documentation, issues)
First occurred: 18 August 2023 at 16:42:27 (1446 occurrences)
Last logged: 17:37:37

Unexpected error fetching electricity_standing_charges data: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/electricity_standing_charges.py", line 72, in async_update_electricity_standing_charges_data
    hass.data[DOMAIN][DATA_ELECTRICITY_STANDING_CHARGES] = await async_refresh_electricity_standing_charges_data(
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/electricity_standing_charges.py", line 42, in async_refresh_electricity_standing_charges_data
    existing_standing_charges[key]["valid_from"] < period_from):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```

```
This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.gas_standing_charges
Source: custom_components/octopus_energy/coordinators/gas_standing_charges.py:42
Integration: Octopus Energy (documentation, issues)
First occurred: 18 August 2023 at 16:42:27 (1446 occurrences)
Last logged: 17:37:38

Unexpected error fetching gas_standing_charges data: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/gas_standing_charges.py", line 72, in async_update_gas_standing_charges_data
    hass.data[DOMAIN][DATA_GAS_STANDING_CHARGES] = await async_refresh_gas_standing_charges_data(
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/gas_standing_charges.py", line 42, in async_refresh_gas_standing_charges_data
    existing_standing_charges[key]["valid_from"] < period_from):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```

**Comment by TheFieryScythe** [comment]
Attempted fix in #380

**Comment by BottlecapDave** [comment]
Hello and sorry that you're receiving this error. I'll take a look at the PR. Out of interest, what tariff are you on so I can add some tests around the fix to try and prevent it happening again in the future?

**Comment by addrum** [comment]
No worries! I'm on the loyal 12M Fixed.

**Comment by BottlecapDave** [comment]
I'm just doing some final checks, along with some other bug fixes, and all going well, will hopefully be out by the weekend.

**Comment by BottlecapDave** [comment]
This should now be fixed in the latest release - https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.2.0
