### ISSUE TITLE
Many Sensors do not get added into HA Energy charts

### ISSUE THREAD

**Issue by tupelotech** [BottlecapDave/HomeAssistant-OctopusEnergy#418]
### Describe the bug

Previous Accumulative Consumption is added as working charts for both Electricity and Gas

### Reproduction steps

Go To settings - Devices and Services - Octopus Energy - 24 entities - Select all or one entity - Enable selected 
Do you want to enable entities - ENABLE
The enabled entities will be added to Home Assistant in 30 seconds

### Expected behaviour

All of the selected entities are expected to arrive in "Sources"
All of the entities are expected to have an associated chart

### Integration Version

V8.2.0 - current version

### Home Assistant Version

2023.9.2 HAOS 10.5 amd64 i386 

### Fresh Install?

Not specified

### Home Assistant Logs

2023-09-22 22:59:11.840 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration octopus_energy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-22 22:59:18.951 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform hassio
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
entity.add_to_platform_start(
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 211, in add_to_platform_start
self._async_read_entity_options()
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 785, in _async_read_entity_options
registry.async_update_entity_options(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1025, in async_update_entity_options
old = self.entities[entity_id]
~~~~~~~~~~~~~^^^^^^^^^^^
File "/usr/local/lib/python3.11/collections/__init__.py", line 1126, in __getitem__
raise KeyError(key)
KeyError: None
2023-09-22 22:59:18.953 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up hassio platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
entity.add_to_platform_start(
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 211, in add_to_platform_start
self._async_read_entity_options()
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 785, in _async_read_entity_options
registry.async_update_entity_options(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1025, in async_update_entity_options
old = self.entities[entity_id]
~~~~~~~~~~~~~^^^^^^^^^^^
File "/usr/local/lib/python3.11/collections/__init__.py", line 1126, in __getitem__
raise KeyError(key)
KeyError: None
2023-09-22 22:59:22.686 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_electricity_21e5039221_2700005666590_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-09-22 22:59:22.690 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_gas_e6e08833752223_7671717003_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-09-22 22:59:22.728 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_electricity_21e5039221_2700005666590_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-09-22 22:59:22.732 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_gas_e6e08833752223_7671717003_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-09-22 23:28:22.418 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.gas_rates] Finished fetching gas_rates data in 0.000 seconds (success: True)
2023-09-22 23:28:22.421 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.gas_standing_charges] Gas standing charges retrieved for G-1R-LOYAL-FIX-12M-23-09-14-J
2023-09-22 23:28:22.421 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.gas_standing_charges] Finished fetching gas_standing_charges data in 0.125 seconds (success: True)
2023-09-22 23:28:22.422 DEBUG (MainThread) [custom_components.octopus_energy.gas.standing_charge] Updating OctopusEnergyGasCurrentStandingCharge
2023-09-22 23:28:22.540 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_standing_charges] Electricity standing charges retrieved for E-1R-GO-VAR-22-10-14-J
2023-09-22 23:28:22.540 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_standing_charges] Finished fetching electricity_standing_charges data in 0.186 seconds (success: True)
2023-09-22 23:28:22.541 DEBUG (MainThread) [custom_components.octopus_energy.electricity.standing_charge] Updating OctopusEnergyElectricityCurrentStandingCharge
2023-09-22 23:28:22.658 DEBUG (MainThread) [custom_components.octopus_energy.gas.previous_accumulative_cost_override] Calculating previous gas consumption cost override for '7671717003/E6E08833752223'...
2023-09-22 23:28:22.659 DEBUG (MainThread) [custom_components.octopus_energy.electricity.previous_accumulative_cost_override] Calculating previous electricity consumption cost override for '2700005666590/21E5039221'...
2023-09-22 23:28:22.659 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.previous_consumption_and_rates] Finished fetching rates_7671717003_E6E08833752223 data in 0.000 seconds (success: True)
2023-09-22 23:28:22.660 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.previous_consumption_and_rates] Finished fetching rates_2700005666590_21E5039221 data in 0.000 seconds (success: True)
2023-09-22 23:28:30.239 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.saving_sessions] Finished fetching saving_sessions data in 0.000 seconds (success: True)
2023-09-22 23:28:30.388 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Finished fetching electricity_rates data in 0.000 seconds (success: True)
2023-09-22 23:28:52.658 DEBUG (MainThread) [custom_components.octopus_energy.gas.previous_accumulative_cost_override] Calculating previous gas consumption cost override for '7671717003/E6E08833752223'...
2023-09-22 23:28:52.659 DEBUG (MainThread) [custom_components.octopus_energy.electricity.previous_accumulative_cost_override] Calculating previous electricity consumption cost override for '2700005666590/21E5039221'...
2023-09-22 23:28:52.659 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.previous_consumption_and_rates] Finished fetching rates_7671717003_E6E08833752223 data in 0.000 seconds (success: True)
2023-09-22 23:28:52.659 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.previous_consumption_and_rates] Finished fetching rates_2700005666590_21E5039221 data in 0.000 seconds (success: True)
2023-09-22 23:29:22.412 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.gas_standing_charges] Gas standing charges retrieved for G-1R-LOYAL-FIX-12M-23-09-14-J
2023-09-22 23:29:22.412 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.gas_standing_charges] Finished fetching gas_standing_charges data in 0.116 seconds (success: True)
2023-09-22 23:29:22.412 DEBUG (MainThread) [custom_components.octopus_energy.gas.standing_charge] Updating OctopusEnergyGasCurrentStandingCharge
2023-09-22 23:29:22.418 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.gas_rates] Finished fetching gas_rates data in 0.000 seconds (success: True)
2023-09-22 23:29:22.473 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_standing_charges] Electricity standing charges retrieved for E-1R-GO-VAR-22-10-14-J
2023-09-22 23:29:22.473 DEBUG (MainThread) [custom_component

**Comment by BottlecapDave** [comment]
Hello and sorry that you're having issues. I've just reinstalled the integration and have had no issues enabling one or many of the disabled entities. 

That reported error looks like something went wrong in HA. Have you tried restarting HA?

**Comment by tupelotech** [comment]
Hi David

Many thanks for looking at this.

Yes I have restarted via both developer tools restart and by re-booting the entire VM. This is running on the HA downloaded VMDK, image in VMware fusion player.

The Electricity previous accumulative has updated overnight, but the gas has not updated as yet.

This is a new install with no other legacy, but it must be due to local issues then. I will try another clean install. Will also setup a Pi4 for it when I get chance. I was hoping the vmdk would be ok.

By the way I noticed that you may be working on pulling through historic data from Octopus. Is that right? . I know the API itself does that.

Cheers
Michael




On 23 Sep 2023, at 11:12, David Kendall ***@***.***> wrote:

﻿

Hello and sorry that you're having issues. I've just reinstalled the integration and have had no issues enabling one or many of the disabled entities.

That reported error looks like something went wrong in HA. Have you tried restarting HA?

**Comment by GTunney** [comment]
I am also having issues with receiving previous gas usage, it seems to have dropped off around the 21st September for me.

**Comment by BottlecapDave** [comment]
@GTunney Are you able to see the previous day's worth of data in the OE dashboard? The processing of my data seems to be a bit slow and I can only see up to the end of the 25th, which the sensor will not pick up by default. If the lag of your gas data is more than 1 day, then you can [adjust the offset](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_account.md#previous-consumption-days-offset) within the main config entry within the OE integration.

**Comment by GTunney** [comment]
> @GTunney Are you able to see the previous day's worth of data in the OE dashboard? The processing of my data seems to be a bit slow and I can only see up to the end of the 25th, which the sensor will not pick up by default. If the lag of your gas data is more than 1 day, then you can [adjust the offset](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_account.md#previous-consumption-days-offset) within the main config entry within the OE integration.

Yes I can see yesterday’s gas and electric usage in the OE dashboard. But only yesterdays electric in HA and gas missing since 21st Sept.

**Comment by BottlecapDave** [comment]
@GTunney  Please raise a separate MR along with debug logs for at least an hour as per the faq.
