### ISSUE TITLE
IndexError: list index out of range in async_refresh_electricity_rates_data

### ISSUE THREAD

**Issue by barking-timber** [BottlecapDave/HomeAssistant-OctopusEnergy#437]
### Describe the bug

Hi, I noticed the following error with `async_refresh_electricity_rates_data` when setting up this integration with my Octopus integration for the first time.

This results in entities don't return any electricity and gas meter data back from Octopus.
The only exception to this is, I can see my tariff names from retrospective `Previous cost override tariff` entities.

Important
* I suspect this might be due to the fact that around Aug 2023 I switched my Agile (electricity) tariff back to Variable. For that reason, I attached API response from Octopus for my meter (mpan, serial and readings redacted).
* the integration found two electricity meters (two mpans) probably because of the above (unsure how Octopus organises this).

I appreciate it, I might be in minority with this issue, but any workaround will be great👍 

PS. Note on the versions. This problem (and this very stack trace) occurred the first time, on 8.1.0 or 8.2.0, and older HASS from Jul 2023, therefore I selected a fresh install, even though this keeps happening on the versions below.

### Reproduction steps

- enable all hidden or disabled integration entities
- restart the Home Assistant

### Expected behaviour

Consumption entities to provide data

### Tariff Code (electricity)
**Update: 5.10.2023**
now `E-1R-AVRO-VAR-21-09-26-M`
before `E-1R-AGILE-FLEX-22-11-25-M`

### Integration Version

8.3.0

### Home Assistant Version

2023.9.2

### Fresh Install?

Fresh install

## The log when restarting Home Assistant
```python
This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.electricity_rates
Source: custom_components/octopus_energy/coordinators/electricity_rates.py:46
Integration: Octopus Energy (documentation, issues)
First occurred: 21:27:05 (4 occurrences)
Last logged: 21:28:10

Unexpected error fetching electricity_rates data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 248, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/electricity_rates.py", line 84, in async_update_electricity_rates_data
    hass.data[DOMAIN][DATA_ELECTRICITY_RATES] = await async_refresh_electricity_rates_data(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/electricity_rates.py", line 46, in async_refresh_electricity_rates_data
    existing_rates[key][-1]["valid_from"] < period_from):
    ~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range

```

## The log when enabling entities
```python
This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.electricity_rates
Source: custom_components/octopus_energy/coordinators/electricity_rates.py:46
Integration: Octopus Energy (documentation, issues)
First occurred: 22 September 2023 at 23:01:37 (709 occurrences)
Last logged: 21:21:10

Unexpected error fetching electricity_rates data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 248, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/electricity_rates.py", line 84, in async_update_electricity_rates_data
    hass.data[DOMAIN][DATA_ELECTRICITY_RATES] = await async_refresh_electricity_rates_data(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/electricity_rates.py", line 46, in async_refresh_electricity_rates_data
    existing_rates[key][-1]["valid_from"] < period_from):
    ~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range

``` 

## Octopus response body to get electricity consumption

`GET https://api.octopus.energy/v1/electricity-meter-points/:mpan/meters/:meter_serial/consumption/`
**Update: 5.10.2023**
Note: this response seems to be for my current mpan - the `count` field keeps increasing. Meanwhile, when calling the same endpoint with the other mpan it returns 404 Not found. This might be the source of the problem.

```json
{
  "count": 10106,
  "next": "https://api.octopus.energy/v1/electricity-meter-points/[REDACTED]/meters/[REDACTED]/consumption/?page=2",
  "previous": null,
  "results": [
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-04T00:30:00+01:00",
      "interval_end": "2023-10-04T01:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-04T00:00:00+01:00",
      "interval_end": "2023-10-04T00:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T23:30:00+01:00",
      "interval_end": "2023-10-04T00:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T23:00:00+01:00",
      "interval_end": "2023-10-03T23:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T22:30:00+01:00",
      "interval_end": "2023-10-03T23:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T22:00:00+01:00",
      "interval_end": "2023-10-03T22:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T21:30:00+01:00",
      "interval_end": "2023-10-03T22:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T21:00:00+01:00",
      "interval_end": "2023-10-03T21:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T20:30:00+01:00",
      "interval_end": "2023-10-03T21:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T20:00:00+01:00",
      "interval_end": "2023-10-03T20:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T19:30:00+01:00",
      "interval_end": "2023-10-03T20:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T19:00:00+01:00",
      "interval_end": "2023-10-03T19:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T18:30:00+01:00",
      "interval_end": "2023-10-03T19:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T18:00:00+01:00",
      "interval_end": "2023-10-03T18:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T17:30:00+01:00",
      "interval_end": "2023-10-03T18:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T17:00:00+01:00",
      "interval_end": "2023-10-03T17:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T16:30:00+01:00",
      "interval_end": "2023-10-03T17:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T16:00:00+01:00",
      "interval_end": "2023-10-03T16:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T15:30:00+01:00",
      "interval_end": "2023-10-03T16:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T15:00:00+01:00",
      "interval_end": "2023-10-03T15:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T14:30:00+01:00",
      "interval_end": "2023-10-03T15:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T14:00:00+01:00",
      "interval_end": "2023-10-03T14:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T13:30:00+01:00",
      "interval_end": "2023-10-03T14:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T13:00:00+01:00",
      "interval_end": "2023-10-03T13:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T12:30:00+01:00",
      "interval_end": "2023-10-03T13:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T12:00:00+01:00",
      "interval_end": "2023-10-03T12:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T11:30:00+01:00",
      "interval_end": "2023-10-03T12:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T11:00:00+01:00",
      "interval_end": "2023-10-03T11:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T10:30:00+01:00",
      "interval_end": "2023-10-03T11:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T10:00:00+01:00",
      "interval_end": "2023-10-03T10:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T09:30:00+01:00",
      "interval_end": "2023-10-03T10:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T09:00:00+01:00",
      "interval_end": "2023-10-03T09:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T08:30:00+01:00",
      "interval_end": "2023-10-03T09:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T08:00:00+01:00",
      "interval_end": "2023-10-03T08:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T07:30:00+01:00",
      "interval_end": "2023-10-03T08:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T07:00:00+01:00",
      "interval_end": "2023-10-03T07:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T06:30:00+01:00",
      "interval_end": "2023-10-03T07:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T06:00:00+01:00",
      "interval_end": "2023-10-03T06:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T05:30:00+01:00",
      "interval_end": "2023-10-03T06:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T05:00:00+01:00",
      "interval_end": "2023-10-03T05:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T04:30:00+01:00",
      "interval_end": "2023-10-03T05:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T04:00:00+01:00",
      "interval_end": "2023-10-03T04:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T03:30:00+01:00",
      "interval_end": "2023-10-03T04:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T03:00:00+01:00",
      "interval_end": "2023-10-03T03:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T02:30:00+01:00",
      "interval_end": "2023-10-03T03:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T02:00:00+01:00",
      "interval_end": "2023-10-03T02:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T01:30:00+01:00",
      "interval_end": "2023-10-03T02:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T01:00:00+01:00",
      "interval_end": "2023-10-03T01:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T00:30:00+01:00",
      "interval_end": "2023-10-03T01:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-03T00:00:00+01:00",
      "interval_end": "2023-10-03T00:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T23:30:00+01:00",
      "interval_end": "2023-10-03T00:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T23:00:00+01:00",
      "interval_end": "2023-10-02T23:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T22:30:00+01:00",
      "interval_end": "2023-10-02T23:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T22:00:00+01:00",
      "interval_end": "2023-10-02T22:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T21:30:00+01:00",
      "interval_end": "2023-10-02T22:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T21:00:00+01:00",
      "interval_end": "2023-10-02T21:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T20:30:00+01:00",
      "interval_end": "2023-10-02T21:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T20:00:00+01:00",
      "interval_end": "2023-10-02T20:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T19:30:00+01:00",
      "interval_end": "2023-10-02T20:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T19:00:00+01:00",
      "interval_end": "2023-10-02T19:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T18:30:00+01:00",
      "interval_end": "2023-10-02T19:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T18:00:00+01:00",
      "interval_end": "2023-10-02T18:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T17:30:00+01:00",
      "interval_end": "2023-10-02T18:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T17:00:00+01:00",
      "interval_end": "2023-10-02T17:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T16:30:00+01:00",
      "interval_end": "2023-10-02T17:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T16:00:00+01:00",
      "interval_end": "2023-10-02T16:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T15:30:00+01:00",
      "interval_end": "2023-10-02T16:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T15:00:00+01:00",
      "interval_end": "2023-10-02T15:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T14:30:00+01:00",
      "interval_end": "2023-10-02T15:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T14:00:00+01:00",
      "interval_end": "2023-10-02T14:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T13:30:00+01:00",
      "interval_end": "2023-10-02T14:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T13:00:00+01:00",
      "interval_end": "2023-10-02T13:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T12:30:00+01:00",
      "interval_end": "2023-10-02T13:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T12:00:00+01:00",
      "interval_end": "2023-10-02T12:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T11:30:00+01:00",
      "interval_end": "2023-10-02T12:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T11:00:00+01:00",
      "interval_end": "2023-10-02T11:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T10:30:00+01:00",
      "interval_end": "2023-10-02T11:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T10:00:00+01:00",
      "interval_end": "2023-10-02T10:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T09:30:00+01:00",
      "interval_end": "2023-10-02T10:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T09:00:00+01:00",
      "interval_end": "2023-10-02T09:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T08:30:00+01:00",
      "interval_end": "2023-10-02T09:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T08:00:00+01:00",
      "interval_end": "2023-10-02T08:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T07:30:00+01:00",
      "interval_end": "2023-10-02T08:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T07:00:00+01:00",
      "interval_end": "2023-10-02T07:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T06:30:00+01:00",
      "interval_end": "2023-10-02T07:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T06:00:00+01:00",
      "interval_end": "2023-10-02T06:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T05:30:00+01:00",
      "interval_end": "2023-10-02T06:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T05:00:00+01:00",
      "interval_end": "2023-10-02T05:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T04:30:00+01:00",
      "interval_end": "2023-10-02T05:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T04:00:00+01:00",
      "interval_end": "2023-10-02T04:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T03:30:00+01:00",
      "interval_end": "2023-10-02T04:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T03:00:00+01:00",
      "interval_end": "2023-10-02T03:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T02:30:00+01:00",
      "interval_end": "2023-10-02T03:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T02:00:00+01:00",
      "interval_end": "2023-10-02T02:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T01:30:00+01:00",
      "interval_end": "2023-10-02T02:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T01:00:00+01:00",
      "interval_end": "2023-10-02T01:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T00:30:00+01:00",
      "interval_end": "2023-10-02T01:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-02T00:00:00+01:00",
      "interval_end": "2023-10-02T00:30:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-01T23:30:00+01:00",
      "interval_end": "2023-10-02T00:00:00+01:00"
    },
    {
      "consumption": [REDACTED],
      "interval_start": "2023-10-01T23:00:00+01:00",
      "interval_end": "2023-10-01T23:30:00+01:00"
    }
  ]
}
```

**Comment by BottlecapDave** [comment]
I've added additional checks in the latest release which should fix this issue.
