### ISSUE TITLE
 Error setting up entry Account for octopus_energy 

### ISSUE THREAD

**Issue by Lord-Chronos** [BottlecapDave/HomeAssistant-OctopusEnergy#450]
### Describe the bug

When integration is started I get 'Failed to set up' in Update Account Info

Logs show the following error:
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/octopus_energy/coordinators/electricity_rates.py:124
Integration: Octopus Energy (documentation, issues)
First occurred: 8:40:53 PM (3 occurrences)
Last logged: 8:47:53 PM

Error setting up entry Account for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 81, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 153, in async_setup_dependencies
    await async_setup_electricity_rates_coordinator(hass, mpan, serial_number, is_smart_meter, is_export_meter)
  File "/config/custom_components/octopus_energy/coordinators/electricity_rates.py", line 124, in async_setup_electricity_rates_coordinator
    hass.data[DOMAIN][coordinator_key] = DataUpdateCoordinator(
                                         ^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataUpdateCoordinator.__init__() got an unexpected keyword argument 'always_update'
```

### Reproduction steps

Start integration with configuration or reload Update Account Info 

### Expected behaviour

The integration sets up with sensors

### Integration Version

v8.41

### Home Assistant Version

Home Assistant 2023.8.4

### Fresh Install?

Fresh install

### Home Assistant Logs

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/octopus_energy/coordinators/electricity_rates.py:124
Integration: Octopus Energy (documentation, issues)
First occurred: 8:40:53 PM (3 occurrences)
Last logged: 8:47:53 PM

Error setting up entry Account for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 81, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 153, in async_setup_dependencies
    await async_setup_electricity_rates_coordinator(hass, mpan, serial_number, is_smart_meter, is_export_meter)
  File "/config/custom_components/octopus_energy/coordinators/electricity_rates.py", line 124, in async_setup_electricity_rates_coordinator
    hass.data[DOMAIN][coordinator_key] = DataUpdateCoordinator(
                                         ^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataUpdateCoordinator.__init__() got an unexpected keyword argument 'always_update'

**Comment by llama85** [comment]
Same here

Plugin Version: 8.4.1
HA Version 2023.8.2 also affected
not a fresh install.

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/octopus_energy/coordinators/electricity_rates.py:124
Integration: Octopus Energy (documentation, issues)
First occurred: 21:11:33 (3 occurrences)
Last logged: 21:15:01

Error setting up entry Account for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 81, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 153, in async_setup_dependencies
    await async_setup_electricity_rates_coordinator(hass, mpan, serial_number, is_smart_meter, is_export_meter)
  File "/config/custom_components/octopus_energy/coordinators/electricity_rates.py", line 124, in async_setup_electricity_rates_coordinator
    hass.data[DOMAIN][coordinator_key] = DataUpdateCoordinator(
                                         ^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataUpdateCoordinator.__init__() got an unexpected keyword argument 'always_update'
```

**Comment by BottlecapDave** [comment]
Hello and sorry that you're both receiving this. I am using a new feature, but forgot to check the minimum required version of Home Assistant. I'm afraid you will need to update to at least 2023.09 in order for the latest update to work. Otherwise you'll need to downgrade the version of this integration to v8.3.0.
