### ISSUE TITLE
Just Updated and lost all automation 

### ISSUE THREAD

**Issue by ChillV2L** [BottlecapDave/HomeAssistant-OctopusEnergy#467]
### Describe the bug

just updated and after restart i got this 
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/121485342/39e68b69-c055-494d-a839-8ec7e6929684)

### Reproduction steps

reproduces on every restart 

### Expected behaviour

N/A

### Integration Version

v8.4.3

### Home Assistant Version

Home Assistant 2023.10.1

### Fresh Install?

After upgrading

### Home Assistant Logs

Logger: homeassistant.setup
Source: setup.py:288
First occurred: 16:48:38 (1 occurrences)
Last logged: 16:48:38

Error during setup of component automation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 252, in async_setup
    await _async_process_config(hass, config, component)
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 972, in _async_process_config
    entities = await _create_automation_entities(hass, updated_automation_configs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 856, in _create_automation_entities
    cond_func = await _async_process_if(hass, name, config_block)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 985, in _async_process_if
    checks.append(await condition.async_from_config(hass, if_config))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 246, in async_from_config
    return cast(ConditionCheckerType, await factory(hass, config))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_automation/condition.py", line 55, in async_condition_from_config
    return trace_condition_function(platform.async_condition_from_config(hass, config))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/device_condition.py", line 256, in async_condition_from_config
    numeric_state_config = condition.numeric_state_validate_config(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 1011, in numeric_state_validate_config
    config[CONF_ENTITY_ID] = er.async_validate_entity_ids(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1380, in async_validate_entity_ids
    return [async_validate_entity_id(registry, item) for item in entity_ids_or_uuids]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1380, in <listcomp>
    return [async_validate_entity_id(registry, item) for item in entity_ids_or_uuids]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1349, in async_validate_entity_id
    raise vol.Invalid(f"Unknown entity registry entry {entity_id_or_uuid}")
voluptuous.error.Invalid: Unknown entity registry entry 06e8f15ef29ea58ffcc3406078b44c3e

Logger: homeassistant.setup
Source: setup.py:185
First occurred: 16:48:51 (1 occurrences)
Last logged: 16:48:51

Setup failed for default_config: (DependencyError(...), 'Could not setup dependencies: automation')

**Comment by BottlecapDave** [comment]
Sorry that you're receiving this issue. Did you update HA or the integration? I'm assuming as you believe it's this integration you only updated the integration? 

As there is no mention of my integration's code in the error logs (seems like a HA bug as this integration doesn't touch automations) and I'm unable to reproduce the issue (I've just updated to the latest version successfully on my test machine), there is very little I can do to fix this issue I'm afraid. The only thing I can suggest is to remove, restart and reinstall the integration.

**Comment by ChillV2L** [comment]
solved the issue by going back to a previous backup, i will try again over the weekend with the octopus update and see if it happens again
