### ISSUE TITLE
Invalid setup error

### ISSUE THREAD

**Issue by IliasEagle** [BottlecapDave/HomeAssistant-OctopusEnergy#477]
### Describe the bug

After the update to v8.4.4 I am getting this error:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/93916516/2b97e10c-040c-4f3c-86a2-a9b7933face9)

### Reproduction steps

Issue appeared after last integration update

### Expected behaviour

Integration is expected to load and all the sensors to report the respective values

### Integration Version

8.4.4

### Home Assistant Version

2023.10.3

### Fresh Install?

After upgrading

### Home Assistant Logs

```
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 16 October 2023 at 06:16:17 (1 occurrences)
Last logged: 16 October 2023 at 06:16:17

Setup failed for custom integration octopus_energy: Unable to import component: No module named 'custom_components.octopus_energy.const'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/octopus_energy/__init__.py", line 4, in <module>
    from custom_components.octopus_energy.utils import get_active_tariff_code
  File "/config/custom_components/octopus_energy/utils/__init__.py", line 7, in <module>
    from ..const import (
ModuleNotFoundError: No module named 'custom_components.octopus_energy.const'

```

**Comment by BottlecapDave** [comment]
Hello and sorry that you're receiving this error. Myself and others have successfully installed this version, so I suspect something went wrong with the download/installation. If you're going through HACS, i suggest you redownload the target version and restart your HA instance.

**Comment by IliasEagle** [comment]
Hello @BottlecapDave, many thanks for your reply. 
I followed your advise and it did work. Appreciate it. 
This is the first time I have an issue like this that simply needs reinstallation so will keep in mind for the future as well. 

Have a wonderful day!

Kind regards, 
Ilias
