### ISSUE TITLE
Failing to Initialise

### ISSUE THREAD

**Issue by fboundy** [BottlecapDave/HomeAssistant-OctopusEnergy#518]
### Describe the bug

Since updating to 8.5.1 the integration won't initialise

### Reproduction steps

Restarted HA. Integration won't initialise.  Suspect it may just be an Octopus timeout but posted the log below for confirmation.

### Expected behaviour

Integration has been faultless for over a year!

### Tariff Code

E-1R

### Integration Version

8.5.1

### Home Assistant Version

2023.11.1

### Fresh Install?

After upgrading

### Home Assistant Logs

Error setting up entry Octopus Energy for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 81, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 125, in async_setup_dependencies
    account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 344, in async_get_account
    await self.async_refresh_token()
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 329, in async_refresh_token
    async with client.post(url, json=payload) as token_response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

**Comment by fboundy** [comment]
Forgot to complete tariff code: AGILE area G

**Comment by fboundy** [comment]
Rolled back to 8.4.4 and all is well... will try to diagnose a bit more tomorrow

**Comment by BottlecapDave** [comment]
Last night the APIs we're having a lot of issues, so I suspect its that. I believe theyve stabilised since then, so you shouldnt have an issue with the latest release.

**Comment by fboundy** [comment]
Thought that might be the case. Will check again today. What confused me was that a couple of my own scripts were able to poll the API OK.
________________________________

**Comment by BottlecapDave** [comment]
the API was intermittently working, at times just being incredibly slow. So if your scripts were more forgiving on timeouts, that's why it would have worked

**Comment by davria18** [comment]
I think I’m getting a similar issue.  I get the following in my logs since upgrading:

Setup failed for octopus_energy: Integration not found.
11:37:31 – (ERROR) setup.py

Any advice gratefully received.

**Comment by BottlecapDave** [comment]
@davria18 your issue looks different. It looks like the installation hasnt been installed correctly. Have you installed it manually or via HACS?

**Comment by davria18** [comment]
I updated it via HACS.

Thanks for your quick reply.

**Comment by davria18** [comment]
That seems to have sorted it.  Thank you so much.
