### ISSUE TITLE
Octopus Fan Club support

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-OctopusEnergy#544]
### Discussed in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/538

<div type='discussions-op-text'>

<sup>Originally posted by **h4rryb** November 17, 2023</sup>
I've just installed this - great set of tools to use on HA! I wondered if there is a way to get the current estimated % saving on the electricity unit rate from the Octopus Fan Club in a similar manner to how it shows in the Octopus dashboard (if that info is accessible via the APIs?)

<img width="1128" alt="Screenshot 2023-11-17 at 21 28 23" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/46907203/f3fb30b1-4c78-419c-9ff5-6dbb468a6f56">

https://www.octopusenergygeneration.com/fan-club/</div>

See original discussion for plan of action, along with some API examples.

**Comment by HITESHLAD1985** [comment]
Yep this would be very useful for me to schedule charging of the battery.

**Comment by BenGlossop09** [comment]
Fellow Fan #1 member here! I would love to see this implemented within the integration.

**Comment by BottlecapDave** [comment]
Update for future self or anyone else who wants to tackle it. I think there are three parts to this ticket, but they don't all need to be provided at once and can be split into separate feature requests. Each part should be at the very least it's own pull request.

1. Provide previous, current and next discount sensors. 

* These sensors should work in a similar way to the previous, current and next rate sensors in that they should a) Combine continous discounts of the same value when calculating the start/end attributes (e.g. if you had a discount of 50% from 10:00-10:30 and 10:30-11:00 and 11:00-11:30, then the start time should be 10:00 and the end time should be 11:30) and b) The previous and next discount should be the previous and next discount that are different to the current discount, not just the next period.
* The above sensors should exist for each fan club the user is a member of
* The above sensors should rely on function(s) for calculating the previous, current and next discount in a similar way to the rate sensors, and these function(s) should be unit tested
* Data for these sensors should be provided via a coordinator, which should refresh every 30 minutes. The coordinator should have the same fallback logic as other coordinators and should be unit tested where possible.
* Docs should be updated to explain these sensors. This should be a new page within the docs. FAQ should be updated with data frequency
* Data diagnostic sensor should be created to indicate when the data was last retrieved.

2. Update rates coordinator to apply discount

* The rates coordinator should be updated to apply any applicable discount to an applicable rate (e.g. if an rate is 0.50 and a discount for that period is 50%, then the rate should be updated to be 0.25).
* If a discount is applied, the rate entry should have a new field called `applied_fan_club_discount` with the discount value that was applied so it's clear why the rate might look different to what OE report.
* This should be similar to how intelligent rates are adjusted outside of the normal period
* The coordinator changes should be fully unit tested.
* Docs should be updated to reflect new field.

3. Update previous consumption cost to apply discount

* The previous consumption cost calculations should be updated to take fan club discounts into account. Because this data is retrieved outside of the normal rates coordinator, its best to tackle this separately.
* The rates breakdowns should make it clear where a discount was applied (same `applied_fan_club_discount` field)
* This should be unit tested.

**Comment by BenGlossop09** [comment]
I've quite a novice so first I've taught myself how to interact with the Graph QL API. I've succeeded doing this directly but am yet to figure out how to do this with python. 
If anyone is working on this in the background, I'd be happy to test code.

**Comment by deemuuu** [comment]
this would be very useful

**Comment by BenGlossop09** [comment]
I found some time to put into this, here is my progress so far.

To start with I wanted to learn how to extract information from the API query using yaml, this is simply because I am more familiar with yaml.

I currently have 4x sensors which extract the following information;
1. Authorization Sensor - To get an auth token from the API to use in the following sensors. I realise this is already part of the OE integration but I have no idea how to access it.
2. Current Discount Sensor - I started with this as it provides the simplest response from the API. This sensor provides the current level of discount. Possible responses are 0, 0.2, 0.5. This is the unaveraged data, 'live' from the turbine.
3. Historic Discount Sensor - Queries for historic fan club discount data and timestamps (the call is not limited to just this information). The API responds with the last 47 data points. This sensor provides the actual discount applied to your account within the given time periods. I reached out to Octopus, they said "We calculate mean power values over 30 minute periods (to match up with the 30minute consumption data we get with smart meters). ...we also include the "historic" component which is the 30 minute average already computed (so you don't have to!)."

Sensor 2 (non-averaged discount data):
![Image](https://github.com/user-attachments/assets/15dedb79-61c0-4e53-bb5d-43e2db95705c)

Sensor 3 (actual discount applied, note the graphed data does not take into account the discount timestamp):
![Image](https://github.com/user-attachments/assets/bd6eea8f-2874-4043-ae81-5c7256222e12)

Sensor 3 (data processed with Apex Charts to show the correct discount at the correct timestamp, as seen in the Octopus Energy Dashboard)
![Image](https://github.com/user-attachments/assets/30a96259-89cc-4ba4-abbf-9cc63f82b576)
![Image](https://github.com/user-attachments/assets/dc3178ab-c09a-4c53-99ca-94ed64e7336f)

Next is to look at forecast data and then figure out how to convert everything to Python so it can be merged with the OE integration. 

Some really interesting [meta data](https://developer.octopus.energy/graphql/reference/objects#api-objects-fanclubmetadataoutput) can be accessed using the API, including wind speed, wind direction and raw kW output.

**Comment by BottlecapDave** [comment]
I was thinking at looking at the first stage of this myself within the next couple of weeks. But as you've started, I'll back off and await your PR.

**Comment by BottlecapDave** [comment]
@BenGlossop09 Did you get any further with bringing this into this integration?

**Comment by BenGlossop09** [comment]
I got stumped with bringing this into the integration. It's just above my abilities right now. I started by trying to figure out how to structure a python script & reference the authorisation token, I probably should've started by learning the language first.
I ended up working on some bug fixes on the yaml instead. 

I won't be offended if you (or anyone else) want to progress this.

**Comment by BottlecapDave** [comment]
No problem at all. I'll probably look at getting the first phase in and do a beta release within the next couple of weeks.

**Comment by BenGlossop09** [comment]
FYI the API return for the 'forecast' request will be 'null' if the current output of the turbine is <=0kW. See below for more detail;

"We set the forecast to null if the current output power of the turbine is less than or equal to 0.
Because the forecasts are based solely on wind-speed (and we fit it to essentially a power-output curve), the forecasts are, in a way, independent of the status of the turbine. Which is bad.
We encoded this logic to prevent us sending out 50% discount notifications (and to show very promising forecasts) in the case where there is an issue with the turbine.
e.g. the turbine might be down for preventative maintenance but the forecasts were projecting it to be blowing a gale.
We base the "is turbine having difficulty" decision on power <= 0, because we don't have access to a "turbine status" component, or equivalent, in any of our source APIs."

**Comment by BottlecapDave** [comment]
There is a beta release for the fan club sensors available at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v15.1.0-beta.1. This has been worked on a little blind as I only had one set of data to go off. I didn't notice the above comment, so this will cause an issue which I'll fix in the next beta release.

The available sensors can be found at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/feat/fan-club-discount/_docs/entities/fan_club.md and work in the same way as the rate sensors do.

**Comment by BottlecapDave** [comment]
The data updates every 30 minutes to try and keep data requests low, so there's a chance it uses a predicted percentage when the site has the actual percentage. The gaps in your history indicate a data issue. Do you have any errors in your logs relating to the integration?

**Comment by BottlecapDave** [comment]
Could I also get about 1 hours worth of [debug logs](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#how-do-i-increase-the-logs-for-the-integration), as this will include the raw responses for this endpoint

**Comment by BenGlossop09** [comment]
I ran debug logging between 1330-1450 today, how can I best share this file with you securely? 

There is an error logged in HA, I hadn't noticed this when I typed my reply yesterday.
```
This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.fan_club_discounts
Source: helpers/update_coordinator.py:380
integration: Octopus Energy (documentation, issues)
First occurred: 22 May 2025 at 00:28:31 (603 occurrences)
Last logged: 13:32:11

Unexpected error fetching A-121F4769_fan_club_discounts data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/fan_club_discounts.py", line 89, in async_update_data
    hass.data[DOMAIN][account_id][DATA_FAN_CLUB_DISCOUNTS] = await async_refresh_fan_club_discounts(
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/config/custom_components/octopus_energy/coordinators/fan_club_discounts.py", line 47, in async_refresh_fan_club_discounts
    result = await client.async_get_fan_club_discounts(account_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 919, in async_get_fan_club_discounts
    return FanClubResponse.parse_obj(response["data"])
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pydantic/main.py", line 1222, in parse_obj
    return cls.model_validate(obj)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
pydantic_core._pydantic_core.ValidationError: 1 validation error for FanClubResponse
fanClubStatus.0.forecast
  Input should be a valid dictionary or instance of ForecastInfo [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
```

**Comment by BottlecapDave** [comment]
I've released https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v15.1.0-beta.2 to fix that issue.

I just need the full lines that have the text `async_get_fan_club_discounts response` which don't have any personal identifiable information as it just contains the discounts.

**Comment by BottlecapDave** [comment]
It would also be good to include the lines which include `custom_components.octopus_energy.coordinators.fan_club_discounts` and `custom_components.octopus_energy.fan_club.`. Again, these shouldn't include any personal identifiable information, but if they did it would just be your account id which you should remove

**Comment by BenGlossop09** [comment]
`custom_components.octopus_energy.fan_club` is now showing in the logs. I've attached another hours worth of logs from beta 2. 
[27_5_25 beta 2 Debug.txt](https://github.com/user-attachments/files/20455089/27_5_25.beta.2.Debug.txt)

**Comment by BottlecapDave** [comment]
I've released https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v15.2.0-beta.1 which should hopefully fix this issue

**Comment by BenGlossop09** [comment]
Something funky seems to be going on as Octopus is reporting a lower discount than the integration. See below a crude match up of the `previous discount` sensor (which I understand is pulled from the `historic` query and so is the confirmed discount values) vs the display in the Octopus dashboard. Note that during the period for which I have compared the integration with the Octopus dashboard, the maximum discount was 20%.
![Image](https://github.com/user-attachments/assets/17d35291-2b10-4c2e-88e2-31d5d6a65a9a)

Logs here [2_6_25.beta.1.Debug.txt](https://github.com/user-attachments/files/20558952/2_6_25.beta.1.Debug.txt)

The section of the graph marked in orange is particularly strange to me - what could be prompting this spike from 0% to 20% & 50% whilst the actual discount is 20% consistently.

**Comment by BottlecapDave** [comment]
This could be a result of the frequency the data is being pulled down. The data is being pulled every 30 minutes. This data includes historic, actual and forecast. Like the rate sensors, the previous, current and next discounts combine time periods across the historic, actual and forecast where the discount value is the same (e.g. if there is 20% discount for 10:00 and 10:30 and the current time is 11:15 and at 20% and the forecast for 12:00 is 20% then the current sensor will report 20% from 10:00 to 13:00 (as current time is extended to the end of the hour as we don't have data available for this point). In our example, this means historic will go from the start of the data to 10:00.

If the data is refreshed at 10:45, but the forecast is updated at 10:50, then we'll be working off the old forecast until around 11:15. I might need to look at updating the data more frequently due to the dynamic nature. 

It might also be better to map the current discount sensor against what OE said during that same period.

I'll take a look at your log when I get a chance.

**Comment by BottlecapDave** [comment]
I've released https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v15.4.0-beta.1 which has the latest features from v15.3.0. I've also increased the frequency of dowloading the data.

**Comment by BenGlossop09** [comment]
I raised an issue with Octopus today as no data has been coming through to their app for a while. They confirmed they're currently having issues with turbine comms at Fan Clubs #1 & #2. When there is no data received from the turbine, the API call response is:
`2025-07-10 19:02:41.177 DEBUG (MainThread) [custom_components.octopus_energy.api_client] async_get_fan_club_discounts response: {'data': {'fanClubStatus': [{'discountSource': '#1 Fan (GBR): Carr Farm', 'current': {'startAt': '2025-07-10T18:02:41.092897+00:00', 'discount': '0.000'}, 'historic': [], 'forecast': None}]}}`

**Comment by BottlecapDave** [comment]
Are any errors raised in this scenario or are the sensors reporting back what is coming back from the API?

**Comment by BottlecapDave** [comment]
That is odd. I'm not able to recreate this behaviour locally with my mocked data. it would be good to know what the attribute values of the event sensor is at the point it dips to 20% discount. If you're comfortable writing and executing SQL, this can be done via the command provided in the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#im-having-issues-with-a-sensor-is-there-any-way-i-can-see-the-attributes-for-a-certain-point-in-time) targeting the event sensor.

If you don't feel comfortable with this, it would be good to create an automation runs when the `octopus_energy_fan_club_discounts` event is fired before the sensor dips to a discount it shouldn't be registering.

**Comment by BottlecapDave** [comment]
Sorry @BenGlossop09 I've only just found some time to look at this. Is there any chance you could get me the data for the `event` sensor for the discounts. I'm curious what the day's worth of data might say. If it's unavailable for 5th august, then any day where you see these drops along with the current rate sensor would be good.
