### ISSUE TITLE
Unexpected error fetching intelligent_dispatches data: 'utf-8' codec can't decode byte 0xe8 in position 11: invalid continuation byte

### ISSUE THREAD

**Issue by jak1502** [BottlecapDave/HomeAssistant-OctopusEnergy#577]
### Describe the bug

After restarting Home Assistant I am getting an error and the integration isn't initialising.

### Reproduction steps

Restart Home Assistant

### Expected behaviour

Integration initialises

### Tariff Code

Unknown

### Integration Version

9.0.2

### Home Assistant Version

2023.11.3

### Fresh Install?

After upgrading

### Home Assistant Logs

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 68, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
                        ^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 11: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_dispatches.py", line 78, in async_update_intelligent_dispatches_data
    dispatches.completed = await async_merge_dispatch_data(hass, account_id, dispatches.completed)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_dispatches.py", line 42, in async_merge_dispatch_data
    saved_dispatches = await store.async_load()
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 133, in async_load
    return await self._load_task
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 142, in _async_load
    return await self._async_load_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 161, in _async_load_data
    data = await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 74, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: 'utf-8' codec can't decode byte 0xe8 in position 11: invalid continuation byte
```

### Confirmation

- [x] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by BottlecapDave** [comment]
Hi. It looks like HA has corrupted the local save for the intelligent dispatches. I'll try and have a look at some defensive code around this at some point this week. However in the mean time, you can resolve this by going into `.storage` within your HA config directory and removing the file `octopus_energy.{{ACCOUNT_ID}}-completed-intelligent-dispatches.json` and reload the integration (if you feel comfortable doing that). This will result in you losing the completed dispatches for the last few days, which could effect the cost calculations for the last few days.

**Comment by BottlecapDave** [comment]
Hello. I've added some recovery logic for this situation. If you upgrade to [v9.1.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v9.1.0), then the integration should work. You'll probably get a warning stating that the local completed dispatches have been removed.
