### ISSUE TITLE
Failed setup: Unexpected error fetching intelligent_dispatches data: 'charge_in_kwh'

### ISSUE THREAD

**Issue by thigger** [BottlecapDave/HomeAssistant-OctopusEnergy#582]
### Describe the bug

Integration was working fine but recently (last few weeks) has stopped working entirely (may correspond with a HA upgrade).
Fails setup of integration
Log error as below

I have tried:
Restarting HA
Upgrading HA
Removing and reinstalling integration
Upgrading integration
Regenerating API key and reinstalling integration

I am also using the Intelligent Octopus integration ( https://github.com/megakid/ha_octopus_intelligent/ ) and this is working fine.

### Reproduction steps

Try to install integration on my system with my Octopus account (Intelligent Octopus, HA 2023.11.2)

### Expected behaviour

Installation sets up and provides entities

### Tariff Code

Sensor does not exist but E-1R-INTELLI-VAR-22-10-14-M  E-1R-OUTGOING-FIX-12M-19-05-13-M  G-1R-VAR-22-11-01-M

### Integration Version

v9.0.2 (but also with releases back to 8.4.4)

### Home Assistant Version

2023.11.2

### Fresh Install?

After upgrading

### Home Assistant Logs

2023-11-27 20:46:27.986 INFO (MainThread) [custom_components.octopus_energy] electricity_price_cap: None
2023-11-27 20:46:27.987 INFO (MainThread) [custom_components.octopus_energy] gas_price_cap: None
2023-11-27 20:46:28.828 DEBUG (MainThread) [custom_components.octopus_energy.api_client] account: {'data': {'account': {'electricityAgreements': [{'meterPoint': {'mpan': 'XXXXXXXXXX', 'meters': [{'makeAndType': 'Kaifa MA120', 'serialNumber': 'XXXXXXXXXX', 'meterType': 'S2ADE', 'smartExportElectricityMeter': {'deviceId': 'XXXXXXXXXXX', 'manufacturer': '1125 - Shenzhen Kaifa Metering', 'model': '31324131', 'firmwareVersion': '17101617'}, 'smartImportElectricityMeter': None}], 'agreements': [{'validFrom': '2023-09-06T23:00:00+00:00', 'validTo': '2024-09-06T23:00:00+00:00', 'tariff': {'tariffCode': 'E-1R-OUTGOING-FIX-12M-19-05-13-M', 'productCode': 'OUTGOING-FIX-12M-19-05-13'}}]}}, {'meterPoint': {'mpan': 'XXXXXXXXXXX', 'meters': [{'makeAndType': 'Kaifa MA120', 'serialNumber': 'XXXXXXXXXX', 'meterType': 'S2ADE', 'smartExportElectricityMeter': None, 'smartImportElectricityMeter': {'deviceId': 'XXXXXXXXXXXXX', 'manufacturer': '1125 - Shenzhen Kaifa Metering', 'model': '31324131', 'firmwareVersion': '17101617'}}], 'agreements': [{'validFrom': '2023-08-05T23:00:00+00:00', 'validTo': None, 'tariff': {'tariffCode': 'E-1R-INTELLI-VAR-22-10-14-M', 'productCode': 'INTELLI-VAR-22-10-14'}}]}}], 'gasAgreements': [{'meterPoint': {'mprn': 'XXXXXXXXXX', 'meters': [{'serialNumber': 'XXXXXXXXXXXXX', 'consumptionUnits': 'm³', 'modelName': 'G4SZV-1', 'mechanism': 'S2', 'smartGasMeter': {'deviceId': 'XXXXXXXXXXXXX', 'manufacturer': '1015 - Flonidan Develco', 'model': '09B33700', 'firmwareVersion': '10030A08'}}], 'agreements': [{'validFrom': '2023-03-31T23:00:00+00:00', 'validTo': None, 'tariff': {'tariffCode': 'G-1R-VAR-22-11-01-M', 'productCode': 'VAR-22-11-01'}}]}}]}}}
2023-11-27 20:46:28.940 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Electricity rates retrieved for XXXXXXXX/XXXXXX (E-1R-OUTGOING-FIX-12M-19-05-13-M);
2023-11-27 20:46:28.941 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Finished fetching ELECTRICITY_RATES_XXXXXXXX_XXXXXXXX data in 0.111 seconds (success: True)
2023-11-27 20:46:29.075 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Electricity rates retrieved for XXXXXXXXX/XXXXXXX (E-1R-INTELLI-VAR-22-10-14-M);
2023-11-27 20:46:29.077 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Finished fetching ELECTRICITY_RATES_XXXXXXXXX_XXXXXXXX data in 0.136 seconds (success: True)
2023-11-27 20:46:29.077 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.account] Finished fetching update_account data in 0.000 seconds (success: True)
2023-11-27 20:46:29.078 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.account] Finished fetching update_account data in 0.000 seconds (success: True)
2023-11-27 20:46:29.370 DEBUG (MainThread) [custom_components.octopus_energy.api_client] async_get_intelligent_dispatches: {'data': {'plannedDispatches': [], 'completedDispatches': []}}
2023-11-27 20:46:29.372 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Intelligent dispatches retrieved for account A-XXXXXXX
2023-11-27 20:46:29.372 DEBUG (MainThread) [custom_components.octopus_energy.intelligent] MOCK_INTELLIGENT_DATA: False
2023-11-27 20:46:29.375 ERROR (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Unexpected error fetching intelligent_dispatches data: 'charge_in_kwh'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_dispatches.py", line 78, in async_update_intelligent_dispatches_data
    dispatches.completed = await async_merge_dispatch_data(hass, account_id, dispatches.completed)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/intelligent_dispatches.py", line 43, in async_merge_dispatch_data
    saved_completed_dispatches = dictionary_list_to_dispatches(saved_dispatches)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/intelligent/__init__.py", line 160, in dictionary_list_to_dispatches
    int(dispatch["charge_in_kwh"]),
        ~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'charge_in_kwh'
2023-11-27 20:46:29.384 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Finished fetching intelligent_dispatches data in 0.306 seconds (success: False)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by BottlecapDave** [comment]
Hello. What data do you get in the other integration for charge_in_kwh? I'm assuming it's either not provided or is a decimal. This is something that is provided by the community as I'm not on this tariff.

**Comment by thigger** [comment]
Thanks - it's not visible in the other integration (it's mostly there as a way to synchronise the target charge of the car and the Octopus setup)

Would it help if I provided some API results? I'm not familiar with the Octopus API but if you let me know what you need I can try to obtain it.

**Comment by BottlecapDave** [comment]
This should now be fixed in [v9.1.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v9.1.0). It looks like it was an issue due to the locally saved completed dispatches.

**Comment by thigger** [comment]
Brilliant, thanks - 9.1.0 works fine.
