### ISSUE TITLE
Unhandled exception when updating sensor.octopus_energy_xxx_octoplus_points fails

### ISSUE THREAD

**Issue by borpin** [BottlecapDave/HomeAssistant-OctopusEnergy#592]
### Describe the bug

Unhandled exception in the log when updating sensor.octopus_energy_xxx_octoplus_points fails

### Reproduction steps

Probably when the Octopus server is busy so difficult to replicate, but can be anticipated. Seems to be the only one that has an unhandled exception (other sensors were timing out this morning).

### Expected behaviour

Exception handled gracefully :)

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-N

### Integration Version

9.1.0

### Home Assistant Version

2023.11.3

### Fresh Install?

After upgrading

### Home Assistant Logs

```
2023-11-30 06:31:16.003 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.octopus_energy_xxx_octoplus_points is taking over 10 seconds
2023-11-30 06:31:21.277 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.octopus_energy_xxx_octoplus_points fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/octoplus/points.py", line 65, in async_update
    self._state = await self._client.async_get_octoplus_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 559, in async_get_octoplus_points
    async with client.post(url, json=payload, headers=headers) as account_response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by borpin** [comment]
You can still handle the exception, raise an error and set the sensor as unavailable. That surely is the correct behaviour?
