### ISSUE TITLE
Latest HA update seems to break this integration

### ISSUE THREAD

**Issue by djdarlo** [BottlecapDave/HomeAssistant-OctopusEnergy#605]
### Describe the bug

I've just updated to Home Assistant Operating System 11.2 and the integration no longer works

### Reproduction steps

Upgrade to HA OS 11.2

### Expected behaviour

Integration works

### Tariff Code

NA

### Integration Version

Latest

### Home Assistant Version

11.2

### Fresh Install?

Not specified

### Home Assistant Logs

currentEntity: event.octopus_energy_electricity_17s0130833_1610028642104_current_day_rates
pastEntity: event.octopus_energy_electricity_17s0130833_1610028642104_previous_day_rates
futureEntity: event.octopus_energy_electricity_17s0130833_1610028642104_next_day_rates
type: custom:octopus-energy-rates-card
cols: 2
showday: true
showpast: false

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/20640104/c28b6335-45c1-4545-8bfe-5dcde0fe0afe)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by darrenmckie** [comment]
I have the same issue.

**Comment by JonSilver** [comment]
Is this just the same issue as #604? I've not updated HAOS but my Octopus integration doesn't start.

**Comment by neildsb** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 8:17:22 am (1 occurrences)
Last logged: 8:17:22 am

Error setting up entry A-F58C561F for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 83, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 127, in async_setup_dependencies
    account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 400, in async_get_account
    await self.async_refresh_token()
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 386, in async_refresh_token
    token_response_body = await self.__async_read_response__(token_response, url)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 1136, in __async_read_response__
    raise ServerError(msg)
custom_components.octopus_energy.api_client.ServerError: DO NOT REPORT - Octopus Energy server error (https://api.octopus.energy/v1/graphql/): 502; <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by JonSilver** [comment]
Same log entries here, Octopus integration won't initialise, but not updated HAOS.

**Comment by plord12** [comment]
Mine seemed to fail at just after 3am -

```
2023-12-05 03:01:26.843 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.octopus_energy_gas_g4p50219241800_3988573002_previous_accumulative_consumption_kwh is taking over 10 seconds
```

I was getting data just before that.  So not sure this is related to HomeAssistant update.

**Comment by craigrouse** [comment]
Pretty sure this is an Octopus server issue, as the Intelligent integration is struggling too, and that has a different codebase.

**Comment by BottlecapDave** [comment]
Any errors that are 502 related are due to octopus APIs. It looks like their Auth service is falling over for graphql based API calls

**Comment by craigrouse** [comment]
It's fixed now.

**Comment by neildsb** [comment]
its working now!!
