### ISSUE TITLE
Failed to initialise after HA restart and now server error

### ISSUE THREAD

**Issue by SoHSolar** [BottlecapDave/HomeAssistant-OctopusEnergy#606]
### Describe the bug

Restarted HA, its been running beautifully for months and now suddenly failed to initialise, then reinstalled and updated and now getting server error when putting in API details and account number.

### Reproduction steps

Unable to input account and API details

### Expected behaviour

I expected it to set my details and create the entities

### Tariff Code

?

### Integration Version

9.1.0

### Home Assistant Version

11.2

### Fresh Install?

After upgrading

### Home Assistant Logs

None available due to restarting HA

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)

**Comment by cunninr2** [comment]
I have same issue with message on configure screen reading - "Failed to connect to OE servers. Please try again later"

**Comment by darrenaf** [comment]
Same issue here.  Gas reading stopped working after updating system last night, restarted all of HomeAssistant, now fails to read any of Octopus Sensors.

**Comment by richardambridge** [comment]
`2023-12-05 08:32:34.977 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Account for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 81, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 125, in async_setup_dependencies
    account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 344, in async_get_account
    await self.async_refresh_token()
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 329, in async_refresh_token
    async with client.post(url, json=payload) as token_response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError`

**Comment by OliveFinch** [comment]
Same here

**Comment by DariukaB** [comment]
Same

**Comment by bmsrecycle** [comment]
I had the same problem where it went offline just after 4am but it has just come back online now at 9.15am.

**Comment by hwb45** [comment]
Having the same problem, was ok after the upgrade then at 04:30 stopped working and after reboot, integration fails to initialise.

**Comment by BottlecapDave** [comment]
As per the message, this is a failure with the APIs and not the integration. Based on comments in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/605, this looks like it has now resolved.

**Comment by BottlecapDave** [comment]
Closing as this seems related to the recent outage.
