### ISSUE TITLE
Errors in logs

### ISSUE THREAD

**Issue by andyblac** [BottlecapDave/HomeAssistant-OctopusEnergy#621]
### Describe the bug

just getting errors in logs, "Timeout error" it could an API server issue, but could you change to just silently exit.

### Reproduction steps

nothing to do

### Expected behaviour

no python crash

### Tariff Code

0

### Integration Version

v9.1.0

### Home Assistant Version

2023.12.1

### Fresh Install?

Fresh install

### Home Assistant Logs

2023-12-11 14:28:00.498 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.octopus_energy_a_82fe21ee_octoplus_points is taking over 10 seconds
2023-12-11 14:28:05.888 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.octopus_energy_a_82fe21ee_octoplus_points fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/octoplus/points.py", line 65, in async_update
    self._state = await self._client.async_get_octoplus_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 559, in async_get_octoplus_points
    async with client.post(url, json=payload, headers=headers) as account_response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 601, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 960, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
This should be downgraded to a warning in the future. I don't want to hide it completely otherwise I'm going to end up with issues raised saying that data isn't being updated (when this is the root cause and at the hands of OE).

**Comment by andyblac** [comment]
understand, the issue was raised just to make you aware of the python crash.

**Comment by BottlecapDave** [comment]
This should be improved in the latest release (v9.2.1)
