### ISSUE TITLE
Blueprint 'Join Savings Session' - notification fails

### ISSUE THREAD

**Issue by pskillen** [BottlecapDave/HomeAssistant-OctopusEnergy#635]
### Describe the bug

When joining the most recent savings session (15 Dec 2023), the automation succeeded in joining the session, but the notification step failed

Unfortunately I can't scroll far enough back in my logs to get the log output, but it seemed to be failing because `event_start` is a `str` and not a `datetime` object

```yaml
action:
  - variables:
      event_start: >-
        {{ state_attr(saving_session_event_entity,
        'available_events')[0]['start'] }}
...
  - service: persistent_notification.create
      message: >
        A new Octopus Energy saving session has been joined. It starts at {{
        event_start.strftime('%H:%M') }} on {{ event_start.day }}/{{
        event_start.month }}
```

### Reproduction steps

1. Add on installed, logged in, configured, etc
2. Create an automation from the `Join Savings Session` blueprint
3. Wait for savings session to be announced

### Expected behaviour

1. Savings session joined - succeeds
2. Notification created - FAILS

### Tariff Code

E-1R-SILVER-FLEX-22-11-25-N

### Integration Version

9.1.0 (latest at present)

### Home Assistant Version

2023.12.1

### Fresh Install?

Not specified

### Home Assistant Logs

.

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by plord12** [comment]
Yes, I saw the same.  My logs contained -

```
2023-12-14 18:30:52.204 ERROR (MainThread) [homeassistant.components.automation.octopus_join_saving_session] Octopus - join saving session: Error executing script. Unexpected error for call_service at pos 1:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
return long_task.result()
^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 833, in handle_service
return await service.entity_service_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/config/custom_components/octopus_energy/octoplus/saving_sessions_events.py", line 66, in async_join_saving_session_event
result = await self._client.async_join_octoplus_saving_session(self._account_id, event_code)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/octopus_energy/api_client/__init__.py", line 578, in async_join_octoplus_saving_session
async with client.post(url, json=payload, headers=headers) as account_response:
File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
self._resp = await self._coro
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 601, in _request
await resp.start(conn)
File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 960, in start
with self._timer:
File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
raise asyncio.TimeoutError from None
TimeoutError
```

**Comment by BottlecapDave** [comment]
Thanks for raising this. It was a quick fix and known issue as pointed out https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/627#discussioncomment-7853342, but I don't expect either of you to know that. The blueprint should now be fixed, so if you reload it and the automations you should get the proper notification.

**Comment by plord12** [comment]
Thanks ... although note that I didn't use the blueprint but instead copied https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/#automation-example_1

Doesn't the stack trace above imply that join_octoplus_saving_session_event (partially) failed ?

**Comment by BottlecapDave** [comment]
The original issue was around the blueprint, which has been resolved. The automation example referenced was built on the basis that OE API can handle demand (which at times it can't), so it's now recommended to use the blueprint structure to accommodate this. The stack trace had the service fail rather than the event. I'll update the docs under the service.

**Comment by plord12** [comment]
> The automation example referenced was built on the basis that OE API can handle demand (which at times it can't)

Ah, thanks, got it.  Presumably loads of folks using your code triggering at the same time !

**Comment by BottlecapDave** [comment]
Yeah potentially. New version that's in the works should hopefully elevate some of that pressure as people will update at different times
