### ISSUE TITLE
"UnboundLocalError: local variable 'start_time' referenced before assignment" when creating a Target Rates sensor

### ISSUE THREAD

**Issue by no1knows** [BottlecapDave/HomeAssistant-OctopusEnergy#65]
Loving the add-on! I get the following error when trying to create a Target Rates sensor called "cheapest_3_hours_intermittent":

```
Logger: homeassistant.components.binary_sensor
Source: custom_components/octopus_energy/binary_sensor.py:142
Integration: Binary Sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 20:42:26 (2 occurrences)
Last logged: 20:42:26

Error adding entities for domain binary_sensor with platform octopus_energy
Error while setting up octopus_energy platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/octopus_energy/binary_sensor.py", line 142, in is_on
    start_time,
UnboundLocalError: local variable 'start_time' referenced before assignment
```
Any pointers? Thank you!

**Comment by BottlecapDave** [comment]
Sorry to hear you've encountered this issue. I've noticed where the error is. A work around until I get a fix in, you could set start time as `00:00` and end time as `23:59`.

**Comment by no1knows** [comment]
Not at all. That seems to have done the trick, thank you! I also have a feature request that I'll post separately :)

**Comment by BottlecapDave** [comment]
This issue should now be fixed properly in the latest release :)
