### ISSUE TITLE
Failed setup

### ISSUE THREAD

**Issue by bluefish8** [BottlecapDave/HomeAssistant-OctopusEnergy#658]
### Describe the bug

Integration was working fine then randomly stopped with no changes to the configuration. Now unable to see any devices or entities. Removed and reinstalled integration but same error occurs. 

### Reproduction steps

No steps taken

### Expected behaviour

Should be able to view entities 

### Tariff Code

Unable to see

### Integration Version

9.2.1

### Home Assistant Version

2023.12.3

### Fresh Install?

Not specified

### Home Assistant Logs

This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.electricity_rates
Source: helpers/update_coordinator.py:300
Integration: Octopus Energy (documentation, issues)
First occurred: 09:25:08 (9 occurrences)
Last logged: 09:27:57

Unexpected error fetching ELECTRICITY_RATES_1200023024701_22J0388324 data: division by zero
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/electricity_rates.py", line 122, in async_update_electricity_rates_data
    hass.data[DOMAIN][key] = await async_refresh_electricity_rates_data(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/electricity_rates.py", line 84, in async_refresh_electricity_rates_data
    raise_rate_events(current,
  File "/config/custom_components/octopus_energy/coordinators/__init__.py", line 111, in raise_rate_events
    __raise_rate_event(next_event_key, next_rates, additional_attributes, fire_event)
  File "/config/custom_components/octopus_energy/coordinators/__init__.py", line 80, in __raise_rate_event
    min_max_average_rates = get_min_max_average_rates(rates)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/utils/rate_information.py", line 159, in get_min_max_average_rates
    "average": round(average_rate / len(rates), 8)
                     ~~~~~~~~~~~~~^~~~~~~~~~~~
ZeroDivisionError: division by zero


### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. This looks like you're pointing at the develop branch instead of actual releases, which is always in flux and is subject to bugs until released. I suggest you point at actual released versions. This issue in particular has been fixed.
