### ISSUE TITLE
Broken Since Update to 11.0.0

### ISSUE THREAD

**Issue by cconnoruk** [BottlecapDave/HomeAssistant-OctopusEnergy#882]
### Describe the bug

I'm getting the following errors -
1. Unable to prepare setup for platform 'octopus_energy.sensor': Platform not found (Exception importing custom_components.octopus_energy.sensor).
2. Unexpected exception importing platform custom_components.octopus_energy.sensor

Just me? (I've tried a load of delete, readd etc.

### Reproduction steps

Error on HA boot up.

### Expected behaviour

It to work ;).

### Tariff Code

0

### Integration Version

11.0.0

### Home Assistant Version

2024.3.3

### Fresh Install?

Fresh install

### Home Assistant Logs

Logger: homeassistant.loader
Source: loader.py:1025
First occurred: 8:27:43 pm (1 occurrences)
Last logged: 8:27:43 pm

Unexpected exception importing platform custom_components.octopus_energy.sensor
Traceback (most recent call last):
  File "/snap/home-assistant-snap/597/lib/python3.12/site-packages/homeassistant/loader.py", line 1025, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/597/lib/python3.12/site-packages/homeassistant/loader.py", line 1058, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/snap/home-assistant-snap/597/custom_components/octopus_energy/sensor.py", line 35, in <module>
    from .cost_tracker.cost_tracker import OctopusEnergyCostTrackerSensor
  File "/var/snap/home-assistant-snap/597/custom_components/octopus_energy/cost_tracker/cost_tracker.py", line 43, in <module>
    class OctopusEnergyCostTrackerSensor(CoordinatorEntity, RestoreSensor):
  File "/var/snap/home-assistant-snap/597/custom_components/octopus_energy/cost_tracker/cost_tracker.py", line 147, in OctopusEnergyCostTrackerSensor
    async def _async_calculate_cost(self, event: Event[EventStateChangedData]):
                                                 ~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'Event' is not subscriptable

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello, sorry you're having an issue. HACS should be enforcing a minimum version of 2024.5 for HA, which is required for this version and beyond of the integration.

**Comment by cconnoruk** [comment]
Updated to 2024.05 and yup it's perfect now. Sorry to have bothered you, thanks for the reply that did allow me to fix my error.
