### ISSUE TITLE
Integration fails to start following latest updates

### ISSUE THREAD

**Issue by S34NW** [BottlecapDave/HomeAssistant-OctopusEnergy#976]
### Describe the bug

The integration fails to load and points to the logs, one of which is an error output during setup

### Reproduction steps

Updated from 11.2.2 to 12.1.0, integration no longer reloads (including after restarting HA)

### Expected behaviour

The integration to load correctly

### Tariff Code

N/A as sensor is not loaded

### Integration Version

12.1.0

### Home Assistant Version

2024.8.1

### Fresh Install?

After upgrading

### Home Assistant Logs

Setup failed for custom integration 'octopus_energy': Unable to import component: No module named 'custom_components.octopus_energy.utils.conversions'

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/octopus_energy/__init__.py", line 13, in <module>
    from .api_client_home_pro import OctopusEnergyHomeProApiClient
  File "/config/custom_components/octopus_energy/api_client_home_pro/__init__.py", line 7, in <module>
    from ..api_client import AuthenticationException, RequestException, ServerException, TimeoutException
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 12, in <module>
    from ..utils import (
  File "/config/custom_components/octopus_energy/utils/__init__.py", line 10, in <module>
    from ..utils.conversions import value_inc_vat_to_pounds
ModuleNotFoundError: No module named 'custom_components.octopus_energy.utils.conversions'
```

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. Sorry you're seeing this issue. I think HACS has failed to install the integration properly. Can you please try and reinstall the integration?

**Comment by S34NW** [comment]
Thanks, that fixed it
